
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.videoInputV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:59.728+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "VideoInput",
                      portName = "VideoInput",
                      targetNamespace = "urn:schemas-pelco-com:service:VideoInput:1",
                      wsdlLocation = "file:a/VideoInputV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.videoInputV1.VideoInputPortType")
                      
public class VideoInputImpl implements VideoInputPortType {

    private static final Logger LOG = Logger.getLogger(VideoInputImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoInputV1.VideoInputPortType#getActiveSessionIds(*
     */
    public SessionList getActiveSessionIds() {
        LOG.info("Executing operation getActiveSessionIds");
        try {
            SessionList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoInputV1.VideoInputPortType#disconnect(java.lang.String  sessionId )*
     */
    public void disconnect(String sessionId) {
        LOG.info("Executing operation disconnect");
        System.out.println(sessionId);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoInputV1.VideoInputPortType#getActiveSessions(java.lang.Integer  activeSessions ,)java.lang.Integer  maxSessions )*
     */
    public void getActiveSessions(javax.xml.ws.Holder<Integer> activeSessions,javax.xml.ws.Holder<Integer> maxSessions) {
        LOG.info("Executing operation getActiveSessions");
        try {
            Integer activeSessionsValue = null;
            activeSessions.value = activeSessionsValue;
            Integer maxSessionsValue = null;
            maxSessions.value = maxSessionsValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoInputV1.VideoInputPortType#getSessionParameters(java.lang.String  sessionId )*
     */
    public com.cmos.ipa.service.video_surveillance.videoInputV1.StreamParameters getSessionParameters(String sessionId) {
        LOG.info("Executing operation getSessionParameters");
        System.out.println(sessionId);
        try {
            com.cmos.ipa.service.video_surveillance.videoInputV1.StreamParameters _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoInputV1.VideoInputPortType#connect(com.cmos.ipa.service.video_surveillance.videoInputV1.StreamParameters  streamParameters )*
     */
    public void connect(javax.xml.ws.Holder<StreamParameters> streamParameters) { 
        LOG.info("Executing operation connect");
        System.out.println(streamParameters.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
