package com.cmos.ipa.service.video_surveillance.videoInputV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This services allows clients to query existing active sessions. 
 * Other uses for this service include initiating a stream, terminating an existing stream and refreshing sessions
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:59.758+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "VideoInput", 
                  wsdlLocation = "file:wsdl/VideoInputV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:VideoInput:1") 
public class VideoInput extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:VideoInput:1", "VideoInput");
    public final static QName VideoInput = new QName("urn:schemas-pelco-com:service:VideoInput:1", "VideoInput");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/VideoInputV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VideoInput.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/VideoInputV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VideoInput(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VideoInput(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VideoInput() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VideoInput(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VideoInput(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VideoInput(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VideoInputPortType
     */
    @WebEndpoint(name = "VideoInput")
    public VideoInputPortType getVideoInput() {
        return super.getPort(VideoInput, VideoInputPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VideoInputPortType
     */
    @WebEndpoint(name = "VideoInput")
    public VideoInputPortType getVideoInput(WebServiceFeature... features) {
        return super.getPort(VideoInput, VideoInputPortType.class, features);
    }

}
