
package com.cmos.ipa.service.video_surveillance.deviceCapability;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:09.620+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ActionNotSupportedFault", targetNamespace = "urn:schemas-pelco-com:fault")
public class ActionNotSupportedFault extends Exception {
    
    private com.cmos.ipa.service.video_surveillance.deviceCapability.ActionNotSupportedFaultType actionNotSupportedFault;

    public ActionNotSupportedFault() {
        super();
    }
    
    public ActionNotSupportedFault(String message) {
        super(message);
    }
    
    public ActionNotSupportedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ActionNotSupportedFault(String message, com.cmos.ipa.service.video_surveillance.deviceCapability.ActionNotSupportedFaultType actionNotSupportedFault) {
        super(message);
        this.actionNotSupportedFault = actionNotSupportedFault;
    }

    public ActionNotSupportedFault(String message, com.cmos.ipa.service.video_surveillance.deviceCapability.ActionNotSupportedFaultType actionNotSupportedFault, Throwable cause) {
        super(message, cause);
        this.actionNotSupportedFault = actionNotSupportedFault;
    }

    public com.cmos.ipa.service.video_surveillance.deviceCapability.ActionNotSupportedFaultType getFaultInfo() {
        return this.actionNotSupportedFault;
    }
}
