package com.cmos.ipa.service.video_surveillance.deviceCapability;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:09.663+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "DeviceCapability", 
                  wsdlLocation = "file:wsdl/DeviceCapability.wsdl",
                  targetNamespace = "http://www.pelco.com/api/DeviceCapability/1") 
public class DeviceCapability extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.pelco.com/api/DeviceCapability/1", "DeviceCapability");
    public final static QName DeviceCapability = new QName("http://www.pelco.com/api/DeviceCapability/1", "DeviceCapability");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/DeviceCapability.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeviceCapability.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/DeviceCapability.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeviceCapability(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceCapability(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceCapability() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DeviceCapability(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeviceCapability(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeviceCapability(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DeviceCapabilityPortType
     */
    @WebEndpoint(name = "DeviceCapability")
    public DeviceCapabilityPortType getDeviceCapability() {
        return super.getPort(DeviceCapability, DeviceCapabilityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceCapabilityPortType
     */
    @WebEndpoint(name = "DeviceCapability")
    public DeviceCapabilityPortType getDeviceCapability(WebServiceFeature... features) {
        return super.getPort(DeviceCapability, DeviceCapabilityPortType.class, features);
    }

}
