
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.deviceCapability;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:09.628+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "DeviceCapability",
                      portName = "DeviceCapability",
                      targetNamespace = "http://www.pelco.com/api/DeviceCapability/1",
                      wsdlLocation = "file:a/DeviceCapability.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType")
                      
public class DeviceCapabilityImpl implements DeviceCapabilityPortType {

    private static final Logger LOG = Logger.getLogger(DeviceCapabilityImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType#getPrimaryStreamCapabilities(com.cmos.ipa.service.video_surveillance.deviceCapability.CompressionFormat  compressionFormat )*
     */
    public StreamConfiguration getPrimaryStreamCapabilities(CompressionFormat compressionFormat) throws InvalidArgumentFault , ActionNotSupportedFault    {
        LOG.info("Executing operation getPrimaryStreamCapabilities");
        System.out.println(compressionFormat);
        try {
            StreamConfiguration _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidArgumentFault("InvalidArgumentFault...");
        //throw new ActionNotSupportedFault("ActionNotSupportedFault...");
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType#getSecondaryStreamCapabilities(com.cmos.ipa.service.video_surveillance.deviceCapability.CompressionFormat  compressionFormat )*
     */
    public StreamSetting getSecondaryStreamCapabilities(CompressionFormat compressionFormat) throws InvalidArgumentFault , ActionNotSupportedFault    {
        LOG.info("Executing operation getSecondaryStreamCapabilities");
        System.out.println(compressionFormat);
        try {
            StreamSetting _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidArgumentFault("InvalidArgumentFault...");
        //throw new ActionNotSupportedFault("ActionNotSupportedFault...");
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType#getDeviceCapability(*
     */
    public Capability getDeviceCapability() throws ActionNotSupportedFault    {
        LOG.info("Executing operation getDeviceCapability");
        try {
            Capability _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActionNotSupportedFault("ActionNotSupportedFault...");
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType#getStreamConfigurations(*
     */
    public StreamConfiguration getStreamConfigurations() throws ActionNotSupportedFault    {
        LOG.info("Executing operation getStreamConfigurations");
        try {
            StreamConfiguration _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActionNotSupportedFault("ActionNotSupportedFault...");
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType#getServices(*
     */
    public Services getServices() throws ActionNotSupportedFault    {
        LOG.info("Executing operation getServices");
        try {
            Services _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ActionNotSupportedFault("ActionNotSupportedFault...");
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.deviceCapability.DeviceCapabilityPortType#getRecommendedStreamConfiguration(com.cmos.ipa.service.video_surveillance.deviceCapability.ServiceNamespaces  serviceNamespaces )*
     */
    public StreamConfiguration getRecommendedStreamConfiguration(ServiceNamespaces serviceNamespaces) throws InvalidArgumentFault , ActionNotSupportedFault    {
        LOG.info("Executing operation getRecommendedStreamConfiguration");
        System.out.println(serviceNamespaces);
        try {
            StreamConfiguration _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidArgumentFault("InvalidArgumentFault...");
        //throw new ActionNotSupportedFault("ActionNotSupportedFault...");
    }

}
