
package com.cmos.ipa.service.video_surveillance.deviceCapability;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:09.611+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidArgumentFault", targetNamespace = "urn:schemas-pelco-com:fault")
public class InvalidArgumentFault extends Exception {
    
    private com.cmos.ipa.service.video_surveillance.deviceCapability.InvalidArgumentFaultType invalidArgumentFault;

    public InvalidArgumentFault() {
        super();
    }
    
    public InvalidArgumentFault(String message) {
        super(message);
    }
    
    public InvalidArgumentFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentFault(String message, com.cmos.ipa.service.video_surveillance.deviceCapability.InvalidArgumentFaultType invalidArgumentFault) {
        super(message);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public InvalidArgumentFault(String message, com.cmos.ipa.service.video_surveillance.deviceCapability.InvalidArgumentFaultType invalidArgumentFault, Throwable cause) {
        super(message, cause);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public com.cmos.ipa.service.video_surveillance.deviceCapability.InvalidArgumentFaultType getFaultInfo() {
        return this.invalidArgumentFault;
    }
}
