package com.cmos.ipa.service.video_surveillance.streamConfigurationV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:43.408+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", name = "StreamConfigurationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface StreamConfigurationPortType {

    @WebMethod(operationName = "GetAllCurrentConfiguration", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#GetAllCurrentConfiguration")
    @RequestWrapper(localName = "GetAllCurrentConfiguration", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetAllCurrentConfiguration")
    @ResponseWrapper(localName = "GetAllCurrentConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetAllCurrentConfigurationResponse")
    @WebResult(name = "result", targetNamespace = "")
    public ConfigurationInfo getAllCurrentConfiguration(
            @WebParam(name = "streamType", targetNamespace = "")
            String streamType
    );

    /**
     * Updates the stream configuration with the settings
     *         passed in. Please refer to the SaveAllSettings in the
     *         StreamConfiguration Issues section for details.
     */
    @WebMethod(operationName = "SaveAllSettings", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#SaveAllSettings")
    @RequestWrapper(localName = "SaveAllSettings", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.SaveAllSettings")
    @ResponseWrapper(localName = "SaveAllSettingsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.SaveAllSettingsResponse")
    public void saveAllSettings(
            @WebParam(name = "streamType", targetNamespace = "")
            String streamType,
            @WebParam(name = "streamSettingsList", targetNamespace = "")
            StreamIDSettingsList streamSettingsList
    );

    @WebMethod(operationName = "SaveSettings", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#SaveSettings")
    @RequestWrapper(localName = "SaveSettings", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.SaveSettings")
    @ResponseWrapper(localName = "SaveSettingsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.SaveSettingsResponse")
    public void saveSettings(
            @WebParam(name = "stream", targetNamespace = "")
            StreamID stream,
            @WebParam(name = "settings", targetNamespace = "")
            StreamSettings settings
    );

    @WebMethod(operationName = "QueryAllOptions", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#QueryAllOptions")
    @RequestWrapper(localName = "QueryAllOptions", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.QueryAllOptions")
    @ResponseWrapper(localName = "QueryAllOptionsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.QueryAllOptionsResponse")
    @WebResult(name = "result", targetNamespace = "")
    public ConfigurationInfo queryAllOptions(
            @WebParam(name = "streamType", targetNamespace = "")
            String streamType,
            @WebParam(name = "streamSettingsList", targetNamespace = "")
            StreamIDSettingsList streamSettingsList
    );

    @WebMethod(operationName = "GetAllSettings", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#GetAllSettings")
    @RequestWrapper(localName = "GetAllSettings", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetAllSettings")
    @ResponseWrapper(localName = "GetAllSettingsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetAllSettingsResponse")
    @WebResult(name = "streamSettingsList", targetNamespace = "")
    public StreamIDSettingsList getAllSettings(
            @WebParam(name = "streamType", targetNamespace = "")
            String streamType
    );

    @WebMethod(operationName = "GetCurrentConfiguration", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#GetCurrentConfiguration")
    @RequestWrapper(localName = "GetCurrentConfiguration", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetCurrentConfiguration")
    @ResponseWrapper(localName = "GetCurrentConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetCurrentConfigurationResponse")
    @WebResult(name = "result", targetNamespace = "")
    public QueryResult getCurrentConfiguration(
            @WebParam(name = "stream", targetNamespace = "")
            StreamID stream
    );

    @WebMethod(operationName = "QueryOptions", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#QueryOptions")
    @RequestWrapper(localName = "QueryOptions", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.QueryOptions")
    @ResponseWrapper(localName = "QueryOptionsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.QueryOptionsResponse")
    @WebResult(name = "result", targetNamespace = "")
    public QueryResult queryOptions(
            @WebParam(name = "stream", targetNamespace = "")
            StreamID stream,
            @WebParam(name = "filter", targetNamespace = "")
            StreamSettings filter
    );

    /**
     * Returns the string identifier of the currently active
     *         preset.
     */
    @WebMethod(operationName = "GetCurrentPresetName", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#GetCurrentPresetName")
    @RequestWrapper(localName = "GetCurrentPresetName", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetCurrentPresetName")
    @ResponseWrapper(localName = "GetCurrentPresetNameResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetCurrentPresetNameResponse")
    @WebResult(name = "presetName", targetNamespace = "")
    public String getCurrentPresetName();

    /**
     * Returns the number of streams supported by the
     *         device.
     */
    @WebMethod(operationName = "GetStreamCount", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#GetStreamCount")
    @RequestWrapper(localName = "GetStreamCount", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetStreamCount")
    @ResponseWrapper(localName = "GetStreamCountResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetStreamCountResponse")
    @WebResult(name = "streamCount", targetNamespace = "")
    public int getStreamCount();

    /**
     * Returns all existing presets.
     */
    @WebMethod(operationName = "GetPresets", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#GetPresets")
    @RequestWrapper(localName = "GetPresets", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetPresets")
    @ResponseWrapper(localName = "GetPresetsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.GetPresetsResponse")
    @WebResult(name = "result", targetNamespace = "")
    public PresetList getPresets();

    /**
     * This operation enables setting of various parameters,
     *         e.g. the bit rate and frame rate, temporarily and dynamically without
     *         recalculating resources. This function will only be allowed to use a
     *         subset of the already identified maximum in order to reserve/allocate
     *         enough space without resetting the stream. It will be tied specifically
     *         to single video stream.
     */
    @WebMethod(operationName = "ApplyDynamicSettings", action = "urn:schemas-pelco-com:service:StreamConfiguration:1#ApplyDynamicSettings")
    @RequestWrapper(localName = "ApplyDynamicSettings", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.ApplyDynamicSettings")
    @ResponseWrapper(localName = "ApplyDynamicSettingsResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.ApplyDynamicSettingsResponse")
    public void applyDynamicSettings(
            @WebParam(name = "streamType", targetNamespace = "")
            String streamType,
            @WebParam(name = "streamSettingsList", targetNamespace = "")
            StreamIDSettingsList streamSettingsList
    );
}
