
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.streamConfigurationV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:43.382+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "StreamConfiguration",
                      portName = "StreamConfiguration",
                      targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1",
                      wsdlLocation = "file:a/StreamConfigurationV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType")
                      
public class StreamConfigurationImpl implements StreamConfigurationPortType {

    private static final Logger LOG = Logger.getLogger(StreamConfigurationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#getAllCurrentConfiguration(java.lang.String  streamType )*
     */
    public ConfigurationInfo getAllCurrentConfiguration(String streamType) {
        LOG.info("Executing operation getAllCurrentConfiguration");
        System.out.println(streamType);
        try {
            ConfigurationInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#saveAllSettings(java.lang.String  streamType ,)com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamIDSettingsList  streamSettingsList )*
     */
    public void saveAllSettings(String streamType,StreamIDSettingsList streamSettingsList) {
        LOG.info("Executing operation saveAllSettings");
        System.out.println(streamType);
        System.out.println(streamSettingsList);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#saveSettings(com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamID  stream ,)com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamSettings  settings )*
     */
    public void saveSettings(StreamID stream,StreamSettings settings) {
        LOG.info("Executing operation saveSettings");
        System.out.println(stream);
        System.out.println(settings);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#queryAllOptions(java.lang.String  streamType ,)com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamIDSettingsList  streamSettingsList )*
     */
    public ConfigurationInfo queryAllOptions(String streamType,StreamIDSettingsList streamSettingsList) {
        LOG.info("Executing operation queryAllOptions");
        System.out.println(streamType);
        System.out.println(streamSettingsList);
        try {
            ConfigurationInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#getAllSettings(java.lang.String  streamType )*
     */
    public StreamIDSettingsList getAllSettings(String streamType) {
        LOG.info("Executing operation getAllSettings");
        System.out.println(streamType);
        try {
            StreamIDSettingsList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#getCurrentConfiguration(com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamID  stream )*
     */
    public QueryResult getCurrentConfiguration(StreamID stream) {
        LOG.info("Executing operation getCurrentConfiguration");
        System.out.println(stream);
        try {
            QueryResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#queryOptions(com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamID  stream ,)com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamSettings  filter )*
     */
    public QueryResult queryOptions(StreamID stream,StreamSettings filter) {
        LOG.info("Executing operation queryOptions");
        System.out.println(stream);
        System.out.println(filter);
        try {
            QueryResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#getCurrentPresetName(*
     */
    public String getCurrentPresetName() {
        LOG.info("Executing operation getCurrentPresetName");
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#getStreamCount(*
     */
    public int getStreamCount() { 
        LOG.info("Executing operation getStreamCount");
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#getPresets(*
     */
    public PresetList getPresets() {
        LOG.info("Executing operation getPresets");
        try {
            PresetList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamConfigurationPortType#applyDynamicSettings(java.lang.String  streamType ,)com.cmos.ipa.service.video_surveillance.streamConfigurationV1.StreamIDSettingsList  streamSettingsList )*
     */
    public void applyDynamicSettings(String streamType,StreamIDSettingsList streamSettingsList) {
        LOG.info("Executing operation applyDynamicSettings");
        System.out.println(streamType);
        System.out.println(streamSettingsList);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
