package com.cmos.ipa.service.video_surveillance.streamConfigurationV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:43.421+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "StreamConfiguration", 
                  wsdlLocation = "file:wsdl/StreamConfigurationV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:StreamConfiguration:1") 
public class StreamConfiguration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:StreamConfiguration:1", "StreamConfiguration");
    public final static QName StreamConfiguration = new QName("urn:schemas-pelco-com:service:StreamConfiguration:1", "StreamConfiguration");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/StreamConfigurationV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StreamConfiguration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/StreamConfigurationV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StreamConfiguration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StreamConfiguration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StreamConfiguration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StreamConfiguration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StreamConfiguration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StreamConfiguration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StreamConfigurationPortType
     */
    @WebEndpoint(name = "StreamConfiguration")
    public StreamConfigurationPortType getStreamConfiguration() {
        return super.getPort(StreamConfiguration, StreamConfigurationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StreamConfigurationPortType
     */
    @WebEndpoint(name = "StreamConfiguration")
    public StreamConfigurationPortType getStreamConfiguration(WebServiceFeature... features) {
        return super.getPort(StreamConfiguration, StreamConfigurationPortType.class, features);
    }

}
