
package com.cmos.ipa.service.video_surveillance.streamConfigurationV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:43.287+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class StreamConfigurationPortType_StreamConfiguration_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:StreamConfiguration:1", "StreamConfiguration");

    private StreamConfigurationPortType_StreamConfiguration_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = StreamConfiguration.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StreamConfiguration ss = new StreamConfiguration(wsdlURL, SERVICE_NAME);
        StreamConfigurationPortType port = ss.getStreamConfiguration();  
        
        {
        System.out.println("Invoking getAllCurrentConfiguration...");
        String _getAllCurrentConfiguration_streamType = "";
        ConfigurationInfo _getAllCurrentConfiguration__return = port.getAllCurrentConfiguration(_getAllCurrentConfiguration_streamType);
        System.out.println("getAllCurrentConfiguration.result=" + _getAllCurrentConfiguration__return);


        }
        {
        System.out.println("Invoking saveAllSettings...");
        String _saveAllSettings_streamType = "";
        StreamIDSettingsList _saveAllSettings_streamSettingsList = null;
        port.saveAllSettings(_saveAllSettings_streamType, _saveAllSettings_streamSettingsList);


        }
        {
        System.out.println("Invoking saveSettings...");
        StreamID _saveSettings_stream = null;
        StreamSettings _saveSettings_settings = null;
        port.saveSettings(_saveSettings_stream, _saveSettings_settings);


        }
        {
        System.out.println("Invoking queryAllOptions...");
        String _queryAllOptions_streamType = "";
        StreamIDSettingsList _queryAllOptions_streamSettingsList = null;
        ConfigurationInfo _queryAllOptions__return = port.queryAllOptions(_queryAllOptions_streamType, _queryAllOptions_streamSettingsList);
        System.out.println("queryAllOptions.result=" + _queryAllOptions__return);


        }
        {
        System.out.println("Invoking getAllSettings...");
        String _getAllSettings_streamType = "";
        StreamIDSettingsList _getAllSettings__return = port.getAllSettings(_getAllSettings_streamType);
        System.out.println("getAllSettings.result=" + _getAllSettings__return);


        }
        {
        System.out.println("Invoking getCurrentConfiguration...");
        StreamID _getCurrentConfiguration_stream = null;
        QueryResult _getCurrentConfiguration__return = port.getCurrentConfiguration(_getCurrentConfiguration_stream);
        System.out.println("getCurrentConfiguration.result=" + _getCurrentConfiguration__return);


        }
        {
        System.out.println("Invoking queryOptions...");
        StreamID _queryOptions_stream = null;
        StreamSettings _queryOptions_filter = null;
        QueryResult _queryOptions__return = port.queryOptions(_queryOptions_stream, _queryOptions_filter);
        System.out.println("queryOptions.result=" + _queryOptions__return);


        }
        {
        System.out.println("Invoking getCurrentPresetName...");
        String _getCurrentPresetName__return = port.getCurrentPresetName();
        System.out.println("getCurrentPresetName.result=" + _getCurrentPresetName__return);


        }
        {
        System.out.println("Invoking getStreamCount...");
        int _getStreamCount__return = port.getStreamCount();
        System.out.println("getStreamCount.result=" + _getStreamCount__return);


        }
        {
        System.out.println("Invoking getPresets...");
        PresetList _getPresets__return = port.getPresets();
        System.out.println("getPresets.result=" + _getPresets__return);


        }
        {
        System.out.println("Invoking applyDynamicSettings...");
        String _applyDynamicSettings_streamType = "";
        StreamIDSettingsList _applyDynamicSettings_streamSettingsList = null;
        port.applyDynamicSettings(_applyDynamicSettings_streamType, _applyDynamicSettings_streamSettingsList);


        }

        System.exit(0);
    }

}
