package com.cmos.ipa.service.video_surveillance.systemManagerLocatorV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:51.323+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:SystemManagerLocator:1", name = "SystemManagerLocatorPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SystemManagerLocatorPortType {

    /**
     * Fecthes the Address and Port number of the System Manager on the network
     *           
     */
    @WebMethod(operationName = "GetLocation", action = "urn:schemas-pelco-com:service:SystemManagerLocator:1#GetLocation")
    @WebResult(name = "GetLocationResponse", targetNamespace = "urn:schemas-pelco-com:service:SystemManagerLocator:1", partName = "parameters")
    public GetLocationResponseType getLocation(
            @WebParam(partName = "header", name = "evHeader", targetNamespace = "urn:schemas-pelco-com:service:SystemManagerLocator:1", header = true)
            GetLocationHeaderType header,
            @WebParam(partName = "parameters", name = "GetLocation", targetNamespace = "urn:schemas-pelco-com:service:SystemManagerLocator:1")
            GetLocationType parameters
    );
}
