
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.audioOutputV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:03.685+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "AudioOutput",
                      portName = "AudioOutput",
                      targetNamespace = "urn:schemas-pelco-com:service:AudioOutput:1",
                      wsdlLocation = "file:a/AudioOutputV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType")
                      
public class AudioOutputImpl implements AudioOutputPortType {

    private static final Logger LOG = Logger.getLogger(AudioOutputImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType#disconnect(java.lang.String  sessionId ,)java.lang.Integer  asyncId )*
     */
    public void disconnect(String sessionId,javax.xml.ws.Holder<Integer> asyncId) {
        LOG.info("Executing operation disconnect");
        System.out.println(sessionId);
        System.out.println(asyncId.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType#connect(com.cmos.ipa.service.video_surveillance.audioOutputV1.StreamParameters  streamParameters ,)java.lang.Integer  asyncId )*
     */
    public void connect(javax.xml.ws.Holder<StreamParameters> streamParameters,javax.xml.ws.Holder<Integer> asyncId) {
        LOG.info("Executing operation connect");
        System.out.println(streamParameters.value);
        System.out.println(asyncId.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType#query(com.cmos.ipa.service.video_surveillance.audioOutputV1.StreamQuery  streamQuery ,)java.lang.Integer  asyncId ,)com.cmos.ipa.service.video_surveillance.audioOutputV1.StreamCatalog  streamCatalog )*
     */
    public void query(StreamQuery streamQuery,javax.xml.ws.Holder<Integer> asyncId,javax.xml.ws.Holder<StreamCatalog> streamCatalog) {
        LOG.info("Executing operation query");
        System.out.println(streamQuery);
        System.out.println(asyncId.value);
        try {
            StreamCatalog streamCatalogValue = null;
            streamCatalog.value = streamCatalogValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType#getActiveSessionIds(*
     */
    public Sessions getActiveSessionIds() {
        LOG.info("Executing operation getActiveSessionIds");
        try {
            Sessions _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType#getActiveSessions(java.lang.Integer  activeSessions ,)java.lang.Integer  maxSessions )*
     */
    public void getActiveSessions(javax.xml.ws.Holder<Integer> activeSessions,javax.xml.ws.Holder<Integer> maxSessions) {
        LOG.info("Executing operation getActiveSessions");
        try {
            Integer activeSessionsValue = null;
            activeSessions.value = activeSessionsValue;
            Integer maxSessionsValue = null;
            maxSessions.value = maxSessionsValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioOutputV1.AudioOutputPortType#refreshSession(java.lang.String  sessionId ,)int  refreshInterval )*
     */
    public void refreshSession(String sessionId,int refreshInterval) {
        LOG.info("Executing operation refreshSession");
        System.out.println(sessionId);
        System.out.println(refreshInterval);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
