package com.cmos.ipa.service.video_surveillance.userAndRoleV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:53.883+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1", name = "UserAndRolePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserAndRolePortType {

    /**
     * Logs out of the System Manager
     * 			
     */
    @WebMethod(operationName = "UserLogout", action = "urn:schemas-pelco-com:service:UserAndRole:1#UserLogout")
    @RequestWrapper(localName = "UserLogout", targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1", className = "com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserLogout")
    @ResponseWrapper(localName = "UserLogoutResponse", targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1", className = "com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserLogoutResponse")
    public void userLogout(
            @WebParam(name = "loginId", targetNamespace = "")
            int loginId
    );

    /**
     * Logs into the System Manager
     * 			
     */
    @WebMethod(operationName = "UserLogin", action = "urn:schemas-pelco-com:service:UserAndRole:1#UserLogin")
    @RequestWrapper(localName = "UserLogin", targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1", className = "com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserLogin")
    @ResponseWrapper(localName = "UserLoginResponse", targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1", className = "com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserLoginResponse")
    @WebResult(name = "loginId", targetNamespace = "")
    public int userLogin(
            @WebParam(name = "user", targetNamespace = "")
            User user,
            @WebParam(name = "pswd", targetNamespace = "")
            Pswd pswd
    );
}
