
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.userAndRoleV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:53.872+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "UserAndRole",
                      portName = "UserAndRole",
                      targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1",
                      wsdlLocation = "file:a/UserAndRoleV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserAndRolePortType")
                      
public class UserAndRoleImpl implements UserAndRolePortType {

    private static final Logger LOG = Logger.getLogger(UserAndRoleImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserAndRolePortType#userLogout(int  loginId )*
     */
    public void userLogout(int loginId) { 
        LOG.info("Executing operation userLogout");
        System.out.println(loginId);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.userAndRoleV1.UserAndRolePortType#userLogin(com.cmos.ipa.service.video_surveillance.userAndRoleV1.User  user ,)com.cmos.ipa.service.video_surveillance.userAndRoleV1.Pswd  pswd )*
     */
    public int userLogin(User user,Pswd pswd) {
        LOG.info("Executing operation userLogin");
        System.out.println(user);
        System.out.println(pswd);
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
