package com.cmos.ipa.service.video_surveillance.userAndRoleV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:53.890+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "UserAndRole", 
                  wsdlLocation = "file:wsdl/UserAndRoleV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:UserAndRole:1") 
public class UserAndRole extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:UserAndRole:1", "UserAndRole");
    public final static QName UserAndRole = new QName("urn:schemas-pelco-com:service:UserAndRole:1", "UserAndRole");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/UserAndRoleV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserAndRole.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/UserAndRoleV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserAndRole(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserAndRole(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAndRole() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserAndRole(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserAndRole(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserAndRole(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserAndRolePortType
     */
    @WebEndpoint(name = "UserAndRole")
    public UserAndRolePortType getUserAndRole() {
        return super.getPort(UserAndRole, UserAndRolePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserAndRolePortType
     */
    @WebEndpoint(name = "UserAndRole")
    public UserAndRolePortType getUserAndRole(WebServiceFeature... features) {
        return super.getPort(UserAndRole, UserAndRolePortType.class, features);
    }

}
