
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.audioInputRtspV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:17:57.868+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "AudioInputRtsp",
                      portName = "AudioInputRtsp",
                      targetNamespace = "urn:schemas-pelco-com:service:AudioInputRtsp:1",
                      wsdlLocation = "file:a/AudioInputRtspV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType")
                      
public class AudioInputRtspImpl implements AudioInputRtspPortType {

    private static final Logger LOG = Logger.getLogger(AudioInputRtspImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#setChannelParameters(com.cmos.ipa.service.video_surveillance.audioInputRtspV1.SetChannelParameters  parameters )*
     */
    public Object setChannelParameters(SetChannelParameters parameters) {
        LOG.info("Executing operation setChannelParameters");
        System.out.println(parameters);
        try {
            Object _return = new Object();
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#setEnabled(boolean  enabled )*
     */
    public void setEnabled(boolean enabled) { 
        LOG.info("Executing operation setEnabled");
        System.out.println(enabled);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#getChannelParameters(int  channelId )*
     */
    public AudioOutSettings getChannelParameters(int channelId) {
        LOG.info("Executing operation getChannelParameters");
        System.out.println(channelId);
        try {
            AudioOutSettings _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#disconnect(int  streamId )*
     */
    public String disconnect(int streamId) {
        LOG.info("Executing operation disconnect");
        System.out.println(streamId);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#getEnabled(*
     */
    public boolean getEnabled() { 
        LOG.info("Executing operation getEnabled");
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#query(*
     */
    public ChannelInfoList query() {
        LOG.info("Executing operation query");
        try {
            ChannelInfoList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#connect(java.lang.String  sourceURI ,)int  channelId ,)int  sessionTimeoutSeconds ,)java.lang.Integer  streamId ,)java.lang.String  streamStatus )*
     */
    public void connect(String sourceURI,int channelId,int sessionTimeoutSeconds,javax.xml.ws.Holder<Integer> streamId,javax.xml.ws.Holder<String> streamStatus) {
        LOG.info("Executing operation connect");
        System.out.println(sourceURI);
        System.out.println(channelId);
        System.out.println(sessionTimeoutSeconds);
        try {
            Integer streamIdValue = null;
            streamId.value = streamIdValue;
            String streamStatusValue = "";
            streamStatus.value = streamStatusValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.audioInputRtspV1.AudioInputRtspPortType#keepAlive(int  streamId )*
     */
    public String keepAlive(int streamId) {
        LOG.info("Executing operation keepAlive");
        System.out.println(streamId);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
