
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.monitorConfigurationV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:23.533+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "MonitorConfiguration",
                      portName = "MonitorConfiguration",
                      targetNamespace = "urn:schemas-pelco-com:service:MonitorConfiguration:1",
                      wsdlLocation = "file:a/MonitorConfigurationV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType")
                      
public class MonitorConfigurationImpl implements MonitorConfigurationPortType {

    private static final Logger LOG = Logger.getLogger(MonitorConfigurationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#resetConfiguration(*
     */
    public void resetConfiguration() { 
        LOG.info("Executing operation resetConfiguration");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#identify(*
     */
    public String identify() {
        LOG.info("Executing operation identify");
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#setChannelConfiguration(com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.ChannelConfig  channelConfig )*
     */
    public void setChannelConfiguration(ChannelConfig channelConfig) {
        LOG.info("Executing operation setChannelConfiguration");
        System.out.println(channelConfig);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#getActiveChannel(*
     */
    public int getActiveChannel() { 
        LOG.info("Executing operation getActiveChannel");
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#getChannelConfiguration(com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.ChannelConfig  channelConfig )*
     */
    public void getChannelConfiguration(javax.xml.ws.Holder<ChannelConfig> channelConfig) { 
        LOG.info("Executing operation getChannelConfiguration");
        System.out.println(channelConfig.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#getLayout(*
     */
    public int getLayout() { 
        LOG.info("Executing operation getLayout");
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#getVolume(*
     */
    public int getVolume() { 
        LOG.info("Executing operation getVolume");
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#setActiveChannel(int  activeChannel )*
     */
    public void setActiveChannel(int activeChannel) { 
        LOG.info("Executing operation setActiveChannel");
        System.out.println(activeChannel);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#getMonitorConfiguration(*
     */
    public MonitorConfig getMonitorConfiguration() {
        LOG.info("Executing operation getMonitorConfiguration");
        try {
            MonitorConfig _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#setMonitorConfiguration(com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfig  monitorConfig )*
     */
    public void setMonitorConfiguration(MonitorConfig monitorConfig) {
        LOG.info("Executing operation setMonitorConfiguration");
        System.out.println(monitorConfig);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#setLayout(int  layout )*
     */
    public void setLayout(int layout) { 
        LOG.info("Executing operation setLayout");
        System.out.println(layout);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#setVolume(int  volume )*
     */
    public void setVolume(int volume) { 
        LOG.info("Executing operation setVolume");
        System.out.println(volume);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.monitorConfigurationV1.MonitorConfigurationPortType#clearAlert(int  channelId )*
     */
    public void clearAlert(int channelId) { 
        LOG.info("Executing operation clearAlert");
        System.out.println(channelId);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
