
package com.cmos.ipa.service.video_surveillance.monitorConfigurationV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:23.447+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class MonitorConfigurationPortType_MonitorConfiguration_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:MonitorConfiguration:1", "MonitorConfiguration");

    private MonitorConfigurationPortType_MonitorConfiguration_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MonitorConfiguration.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MonitorConfiguration ss = new MonitorConfiguration(wsdlURL, SERVICE_NAME);
        MonitorConfigurationPortType port = ss.getMonitorConfiguration();  
        
        {
        System.out.println("Invoking resetConfiguration...");
        port.resetConfiguration();


        }
        {
        System.out.println("Invoking identify...");
        String _identify__return = port.identify();
        System.out.println("identify.result=" + _identify__return);


        }
        {
        System.out.println("Invoking setChannelConfiguration...");
        ChannelConfig _setChannelConfiguration_channelConfig = null;
        port.setChannelConfiguration(_setChannelConfiguration_channelConfig);


        }
        {
        System.out.println("Invoking getActiveChannel...");
        int _getActiveChannel__return = port.getActiveChannel();
        System.out.println("getActiveChannel.result=" + _getActiveChannel__return);


        }
        {
        System.out.println("Invoking getChannelConfiguration...");
        ChannelConfig _getChannelConfiguration_channelConfigVal = null;
        javax.xml.ws.Holder<ChannelConfig> _getChannelConfiguration_channelConfig = new javax.xml.ws.Holder<ChannelConfig>(_getChannelConfiguration_channelConfigVal);
        port.getChannelConfiguration(_getChannelConfiguration_channelConfig);

        System.out.println("getChannelConfiguration._getChannelConfiguration_channelConfig=" + _getChannelConfiguration_channelConfig.value);

        }
        {
        System.out.println("Invoking getLayout...");
        int _getLayout__return = port.getLayout();
        System.out.println("getLayout.result=" + _getLayout__return);


        }
        {
        System.out.println("Invoking getVolume...");
        int _getVolume__return = port.getVolume();
        System.out.println("getVolume.result=" + _getVolume__return);


        }
        {
        System.out.println("Invoking setActiveChannel...");
        int _setActiveChannel_activeChannel = 0;
        port.setActiveChannel(_setActiveChannel_activeChannel);


        }
        {
        System.out.println("Invoking getMonitorConfiguration...");
        MonitorConfig _getMonitorConfiguration__return = port.getMonitorConfiguration();
        System.out.println("getMonitorConfiguration.result=" + _getMonitorConfiguration__return);


        }
        {
        System.out.println("Invoking setMonitorConfiguration...");
        MonitorConfig _setMonitorConfiguration_monitorConfig = null;
        port.setMonitorConfiguration(_setMonitorConfiguration_monitorConfig);


        }
        {
        System.out.println("Invoking setLayout...");
        int _setLayout_layout = 0;
        port.setLayout(_setLayout_layout);


        }
        {
        System.out.println("Invoking setVolume...");
        int _setVolume_volume = 0;
        port.setVolume(_setVolume_volume);


        }
        {
        System.out.println("Invoking clearAlert...");
        int _clearAlert_channelId = 0;
        port.clearAlert(_clearAlert_channelId);


        }

        System.exit(0);
    }

}
