package com.cmos.ipa.service.video_surveillance.cameraConfigurationV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * 
 * 		
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:06.546+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "CameraConfiguration", 
                  wsdlLocation = "file:wsdl/CameraConfigurationV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:CameraConfiguration:1") 
public class CameraConfiguration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:CameraConfiguration:1", "CameraConfiguration");
    public final static QName CameraConfiguration = new QName("urn:schemas-pelco-com:service:CameraConfiguration:1", "CameraConfiguration");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/CameraConfigurationV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CameraConfiguration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/CameraConfigurationV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CameraConfiguration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CameraConfiguration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CameraConfiguration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CameraConfiguration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CameraConfiguration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CameraConfiguration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CameraConfigurationPortType
     */
    @WebEndpoint(name = "CameraConfiguration")
    public CameraConfigurationPortType getCameraConfiguration() {
        return super.getPort(CameraConfiguration, CameraConfigurationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CameraConfigurationPortType
     */
    @WebEndpoint(name = "CameraConfiguration")
    public CameraConfigurationPortType getCameraConfiguration(WebServiceFeature... features) {
        return super.getPort(CameraConfiguration, CameraConfigurationPortType.class, features);
    }

}
