
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.cameraConfigurationV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:06.522+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "CameraConfiguration",
                      portName = "CameraConfiguration",
                      targetNamespace = "urn:schemas-pelco-com:service:CameraConfiguration:1",
                      wsdlLocation = "file:a/CameraConfigurationV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.cameraConfigurationV1.CameraConfigurationPortType")
                      
public class CameraConfigurationImpl implements CameraConfigurationPortType {

    private static final Logger LOG = Logger.getLogger(CameraConfigurationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.cameraConfigurationV1.CameraConfigurationPortType#getConfiguration(*
     */
    public CameraConfig getConfiguration() {
        LOG.info("Executing operation getConfiguration");
        try {
            CameraConfig _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.cameraConfigurationV1.CameraConfigurationPortType#resetConfiguration(*
     */
    public void resetConfiguration() { 
        LOG.info("Executing operation resetConfiguration");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.cameraConfigurationV1.CameraConfigurationPortType#setConfiguration(com.cmos.ipa.service.video_surveillance.cameraConfigurationV1.CameraConfig  cameraConfig )*
     */
    public void setConfiguration(CameraConfig cameraConfig) {
        LOG.info("Executing operation setConfiguration");
        System.out.println(cameraConfig);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
