
package com.cmos.ipa.service.video_surveillance.cameraConfigurationV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:06.440+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class CameraConfigurationPortType_CameraConfiguration_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:CameraConfiguration:1", "CameraConfiguration");

    private CameraConfigurationPortType_CameraConfiguration_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CameraConfiguration.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CameraConfiguration ss = new CameraConfiguration(wsdlURL, SERVICE_NAME);
        CameraConfigurationPortType port = ss.getCameraConfiguration();  
        
        {
        System.out.println("Invoking getConfiguration...");
        CameraConfig _getConfiguration__return = port.getConfiguration();
        System.out.println("getConfiguration.result=" + _getConfiguration__return);


        }
        {
        System.out.println("Invoking resetConfiguration...");
        port.resetConfiguration();


        }
        {
        System.out.println("Invoking setConfiguration...");
        CameraConfig _setConfiguration_cameraConfig = null;
        port.setConfiguration(_setConfiguration_cameraConfig);


        }

        System.exit(0);
    }

}
