package com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The RelayArrayConfiguration service allows multiple relays to be controlled from a single service. Each relay in the service is individually identified by an relayId, which is an index into the relay array. Each RelayArrayConfiguration service should be contained within a RelayArray device.
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:35.179+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "RelayArrayConfiguration", 
                  wsdlLocation = "file:wsdl/RelayArrayConfigurationV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1") 
public class RelayArrayConfiguration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:RelayArrayConfiguration:1", "RelayArrayConfiguration");
    public final static QName RelayArrayConfiguration = new QName("urn:schemas-pelco-com:service:RelayArrayConfiguration:1", "RelayArrayConfiguration");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/RelayArrayConfigurationV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RelayArrayConfiguration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/RelayArrayConfigurationV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RelayArrayConfiguration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RelayArrayConfiguration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RelayArrayConfiguration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RelayArrayConfiguration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RelayArrayConfiguration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RelayArrayConfiguration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RelayArrayConfigurationPortType
     */
    @WebEndpoint(name = "RelayArrayConfiguration")
    public RelayArrayConfigurationPortType getRelayArrayConfiguration() {
        return super.getPort(RelayArrayConfiguration, RelayArrayConfigurationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RelayArrayConfigurationPortType
     */
    @WebEndpoint(name = "RelayArrayConfiguration")
    public RelayArrayConfigurationPortType getRelayArrayConfiguration(WebServiceFeature... features) {
        return super.getPort(RelayArrayConfiguration, RelayArrayConfigurationPortType.class, features);
    }

}
