
package com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:35.069+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class RelayArrayConfigurationPortType_RelayArrayConfiguration_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:RelayArrayConfiguration:1", "RelayArrayConfiguration");

    private RelayArrayConfigurationPortType_RelayArrayConfiguration_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = RelayArrayConfiguration.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RelayArrayConfiguration ss = new RelayArrayConfiguration(wsdlURL, SERVICE_NAME);
        RelayArrayConfigurationPortType port = ss.getRelayArrayConfiguration();  
        
        {
        System.out.println("Invoking getRelayStates...");
        RelayStates _getRelayStates__return = port.getRelayStates();
        System.out.println("getRelayStates.result=" + _getRelayStates__return);


        }
        {
        System.out.println("Invoking resetConfiguration...");
        int _resetConfiguration_relayID = 0;
        port.resetConfiguration(_resetConfiguration_relayID);


        }
        {
        System.out.println("Invoking getArraySize...");
        int _getArraySize__return = port.getArraySize();
        System.out.println("getArraySize.result=" + _getArraySize__return);


        }
        {
        System.out.println("Invoking triggerRelay...");
        int _triggerRelay_relayID = 0;
        int _triggerRelay_mode = 0;
        RelayConfig _triggerRelay_relayConfig = null;
        port.triggerRelay(_triggerRelay_relayID, _triggerRelay_mode, _triggerRelay_relayConfig);


        }
        {
        System.out.println("Invoking setConfiguration...");
        int _setConfiguration_relayID = 0;
        RelayConfig _setConfiguration_relayConfig = null;
        port.setConfiguration(_setConfiguration_relayID, _setConfiguration_relayConfig);


        }
        {
        System.out.println("Invoking getConfiguration...");
        int _getConfiguration_relayID = 0;
        RelayConfig _getConfiguration__return = port.getConfiguration(_getConfiguration_relayID);
        System.out.println("getConfiguration.result=" + _getConfiguration__return);


        }

        System.exit(0);
    }

}
