
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:35.147+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "RelayArrayConfiguration",
                      portName = "RelayArrayConfiguration",
                      targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1",
                      wsdlLocation = "file:a/RelayArrayConfigurationV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType")
                      
public class RelayArrayConfigurationImpl implements RelayArrayConfigurationPortType {

    private static final Logger LOG = Logger.getLogger(RelayArrayConfigurationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType#getRelayStates(*
     */
    public RelayStates getRelayStates() {
        LOG.info("Executing operation getRelayStates");
        try {
            RelayStates _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType#resetConfiguration(int  relayID )*
     */
    public void resetConfiguration(int relayID) { 
        LOG.info("Executing operation resetConfiguration");
        System.out.println(relayID);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType#getArraySize(*
     */
    public int getArraySize() { 
        LOG.info("Executing operation getArraySize");
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType#triggerRelay(int  relayID ,)int  mode ,)com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayConfig  relayConfig )*
     */
    public void triggerRelay(int relayID,int mode,RelayConfig relayConfig) {
        LOG.info("Executing operation triggerRelay");
        System.out.println(relayID);
        System.out.println(mode);
        System.out.println(relayConfig);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType#setConfiguration(int  relayID ,)com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayConfig  relayConfig )*
     */
    public void setConfiguration(int relayID,RelayConfig relayConfig) {
        LOG.info("Executing operation setConfiguration");
        System.out.println(relayID);
        System.out.println(relayConfig);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.RelayArrayConfigurationPortType#getConfiguration(int  relayID )*
     */
    public RelayConfig getConfiguration(int relayID) {
        LOG.info("Executing operation getConfiguration");
        System.out.println(relayID);
        try {
            RelayConfig _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
