package com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:35.168+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", name = "RelayArrayConfigurationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface RelayArrayConfigurationPortType {

    /**
     * Returns the current state and enabled state of the relays contained within the range indicated by relayStates.offset and relayStates.length.
     */
    @WebMethod(operationName = "GetRelayStates", action = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1#GetRelayStates")
    @RequestWrapper(localName = "GetRelayStates", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.GetRelayStates")
    @ResponseWrapper(localName = "GetRelayStatesResponse", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.GetRelayStatesResponse")
    @WebResult(name = "relayStates", targetNamespace = "")
    public RelayStates getRelayStates();

    /**
     * Resets the relay to its factory default settings.
     */
    @WebMethod(operationName = "ResetConfiguration", action = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1#ResetConfiguration")
    @RequestWrapper(localName = "ResetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.ResetConfiguration")
    @ResponseWrapper(localName = "ResetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.ResetConfigurationResponse")
    public void resetConfiguration(
            @WebParam(name = "relayID", targetNamespace = "")
            int relayID
    );

    /**
     * Returns the number of relays contained in the relay array.
     */
    @WebMethod(operationName = "GetArraySize", action = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1#GetArraySize")
    @RequestWrapper(localName = "GetArraySize", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.GetArraySize")
    @ResponseWrapper(localName = "GetArraySizeResponse", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.GetArraySizeResponse")
    @WebResult(name = "size", targetNamespace = "")
    public int getArraySize();

    /**
     * Triggers the relay in the indicated mode.
     */
    @WebMethod(operationName = "TriggerRelay", action = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1#TriggerRelay")
    @RequestWrapper(localName = "TriggerRelay", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.TriggerRelay")
    @ResponseWrapper(localName = "TriggerRelayResponse", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.TriggerRelayResponse")
    public void triggerRelay(
            @WebParam(name = "relayID", targetNamespace = "")
            int relayID,
            @WebParam(name = "mode", targetNamespace = "")
            int mode,
            @WebParam(name = "relayConfig", targetNamespace = "")
            RelayConfig relayConfig
    );

    /**
     * Sets the configuration of the relay indicated by relayId.
     */
    @WebMethod(operationName = "SetConfiguration", action = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1#SetConfiguration")
    @RequestWrapper(localName = "SetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.SetConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.SetConfigurationResponse")
    public void setConfiguration(
            @WebParam(name = "relayID", targetNamespace = "")
            int relayID,
            @WebParam(name = "relayConfig", targetNamespace = "")
            RelayConfig relayConfig
    );

    /**
     * Returns the configuration of the relay.
     */
    @WebMethod(operationName = "GetConfiguration", action = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1#GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:RelayArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.relayArrayConfigurationV1.GetConfigurationResponse")
    @WebResult(name = "relayConfig", targetNamespace = "")
    public RelayConfig getConfiguration(
            @WebParam(name = "relayID", targetNamespace = "")
            int relayID
    );
}
