package com.cmos.ipa.service.video_surveillance.videoAnalyticsV2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:56.922+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", name = "VideoAnalyticsPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface VideoAnalyticsPortType {

    @WebMethod(operationName = "ExecuteProfile", action = "urn:schemas-pelco-com:service:VideoAnalytics:2#ExecuteProfile")
    @RequestWrapper(localName = "ExecuteProfile", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.ExecuteProfile")
    @ResponseWrapper(localName = "ExecuteProfileResponse", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.ExecuteProfileResponse")
    public void executeProfile(
            @WebParam(name = "id", targetNamespace = "")
            int id
    );

    @WebMethod(operationName = "StopProfile", action = "urn:schemas-pelco-com:service:VideoAnalytics:2#StopProfile")
    @RequestWrapper(localName = "StopProfile", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.StopProfile")
    @ResponseWrapper(localName = "StopProfileResponse", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.StopProfileResponse")
    public void stopProfile(
            @WebParam(name = "profileId", targetNamespace = "")
            int profileId
    );

    @WebMethod(operationName = "GetProfileList", action = "urn:schemas-pelco-com:service:VideoAnalytics:2#GetProfileList")
    @RequestWrapper(localName = "GetProfileList", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.GetProfileList")
    @ResponseWrapper(localName = "GetProfileListResponse", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.GetProfileListResponse")
    @WebResult(name = "profileList", targetNamespace = "")
    public ProfileList getProfileList();

    @WebMethod(operationName = "GetActiveProfile", action = "urn:schemas-pelco-com:service:VideoAnalytics:2#GetActiveProfile")
    @RequestWrapper(localName = "GetActiveProfile", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.GetActiveProfile")
    @ResponseWrapper(localName = "GetActiveProfileResponse", targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2", className = "com.cmos.ipa.service.video_surveillance.videoAnalyticsV2.GetActiveProfileResponse")
    @WebResult(name = "profileId", targetNamespace = "")
    public int getActiveProfile();
}
