package com.cmos.ipa.service.video_surveillance.videoAnalyticsV2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:56.930+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "VideoAnalytics", 
                  wsdlLocation = "file:wsdl/VideoAnalyticsV2.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:VideoAnalytics:2") 
public class VideoAnalytics extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:VideoAnalytics:2", "VideoAnalytics");
    public final static QName VideoAnalytics2 = new QName("urn:schemas-pelco-com:service:VideoAnalytics:2", "VideoAnalytics2");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/VideoAnalyticsV2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VideoAnalytics.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/VideoAnalyticsV2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VideoAnalytics(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VideoAnalytics(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VideoAnalytics() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VideoAnalytics(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VideoAnalytics(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VideoAnalytics(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VideoAnalyticsPortType
     */
    @WebEndpoint(name = "VideoAnalytics2")
    public VideoAnalyticsPortType getVideoAnalytics2() {
        return super.getPort(VideoAnalytics2, VideoAnalyticsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VideoAnalyticsPortType
     */
    @WebEndpoint(name = "VideoAnalytics2")
    public VideoAnalyticsPortType getVideoAnalytics2(WebServiceFeature... features) {
        return super.getPort(VideoAnalytics2, VideoAnalyticsPortType.class, features);
    }

}
