
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.softwareUpdateV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:40.457+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "SoftwareUpdate",
                      portName = "SoftwareUpdate",
                      targetNamespace = "urn:schemas-pelco-com:service:SoftwareUpdate:1",
                      wsdlLocation = "file:a/SoftwareUpdateV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.softwareUpdateV1.SoftwareUpdatePortType")
                      
public class SoftwareUpdateImpl implements SoftwareUpdatePortType {

    private static final Logger LOG = Logger.getLogger(SoftwareUpdateImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.softwareUpdateV1.SoftwareUpdatePortType#getModules(*
     */
    public ModuleCatalog getModules() {
        LOG.info("Executing operation getModules");
        try {
            ModuleCatalog _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
