package com.cmos.ipa.service.video_surveillance.lensControlV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:18.139+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", name = "LensControlPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface LensControlPortType {

    @WebMethod(operationName = "GetMaxDigitalMag", action = "urn:schemas-pelco-com:service:LensControl:1#GetMaxDigitalMag")
    @RequestWrapper(localName = "GetMaxDigitalMag", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxDigitalMag")
    @ResponseWrapper(localName = "GetMaxDigitalMagResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxDigitalMagResponse")
    @WebResult(name = "magnification", targetNamespace = "")
    public long getMaxDigitalMag();

    /**
     * Returns the maximum possible angle-of-view of the lens.
     */
    @WebMethod(operationName = "GetMaxAOV", action = "urn:schemas-pelco-com:service:LensControl:1#GetMaxAOV")
    @RequestWrapper(localName = "GetMaxAOV", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxAOV")
    @ResponseWrapper(localName = "GetMaxAOVResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxAOVResponse")
    @WebResult(name = "aovMax", targetNamespace = "")
    public long getMaxAOV();

    /**
     * 
     */
    @WebMethod(operationName = "Stop", action = "urn:schemas-pelco-com:service:LensControl:1#Stop")
    @RequestWrapper(localName = "Stop", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.Stop")
    @ResponseWrapper(localName = "StopResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.StopResponse")
    public void stop();

    /**
     * Turns auto focus on/off.
     */
    @WebMethod(operationName = "AutoFocus", action = "urn:schemas-pelco-com:service:LensControl:1#AutoFocus")
    @RequestWrapper(localName = "AutoFocus", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.AutoFocus")
    @ResponseWrapper(localName = "AutoFocusResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.AutoFocusResponse")
    public void autoFocus(
            @WebParam(name = "onOff", targetNamespace = "")
            int onOff
    );

    /**
     * Gets the total maximum magnification of the lens (GetMaxMag = GetMaxOpticalMag * GetMaxDigitalMag). Total zoom magnification is calculated by multiplying the optical zoom by the digital zoom.
     */
    @WebMethod(operationName = "GetMaxMag", action = "urn:schemas-pelco-com:service:LensControl:1#GetMaxMag")
    @RequestWrapper(localName = "GetMaxMag", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxMag")
    @ResponseWrapper(localName = "GetMaxMagResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxMagResponse")
    @WebResult(name = "magnification", targetNamespace = "")
    public long getMaxMag();

    /**
     * Changes the magnification of the lens, continuously zooming in or out until a limit is reached.
     */
    @WebMethod(operationName = "Zoom", action = "urn:schemas-pelco-com:service:LensControl:1#Zoom")
    @RequestWrapper(localName = "Zoom", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.Zoom")
    @ResponseWrapper(localName = "ZoomResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.ZoomResponse")
    public void zoom(
            @WebParam(name = "inOut", targetNamespace = "")
            long inOut
    );

    /**
     * Focuses the lens near/far, continuously until a limit is reached.
     */
    @WebMethod(operationName = "Focus", action = "urn:schemas-pelco-com:service:LensControl:1#Focus")
    @RequestWrapper(localName = "Focus", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.Focus")
    @ResponseWrapper(localName = "FocusResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.FocusResponse")
    public void focus(
            @WebParam(name = "nearFar", targetNamespace = "")
            long nearFar
    );

    /**
     * Sets the current magnification of the lens. Magnification must be between 1 and MaxMag value.
     */
    @WebMethod(operationName = "SetMag", action = "urn:schemas-pelco-com:service:LensControl:1#SetMag")
    @RequestWrapper(localName = "SetMag", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.SetMag")
    @ResponseWrapper(localName = "SetMagResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.SetMagResponse")
    public void setMag(
            @WebParam(name = "magnification", targetNamespace = "")
            long magnification
    );

    /**
     * Turns auto iris on/off.
     */
    @WebMethod(operationName = "AutoIris", action = "urn:schemas-pelco-com:service:LensControl:1#AutoIris")
    @RequestWrapper(localName = "AutoIris", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.AutoIris")
    @ResponseWrapper(localName = "AutoIrisResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.AutoIrisResponse")
    public void autoIris(
            @WebParam(name = "onOff", targetNamespace = "")
            int onOff
    );

    /**
     * Returns the maximum optical magnification of the lens.
     */
    @WebMethod(operationName = "GetMaxOpticalMag", action = "urn:schemas-pelco-com:service:LensControl:1#GetMaxOpticalMag")
    @RequestWrapper(localName = "GetMaxOpticalMag", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxOpticalMag")
    @ResponseWrapper(localName = "GetMaxOpticalMagResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMaxOpticalMagResponse")
    @WebResult(name = "magnification", targetNamespace = "")
    public long getMaxOpticalMag();

    /**
     * Opens/closes the lens iris, continuously until a limit is reached.
     */
    @WebMethod(operationName = "Iris", action = "urn:schemas-pelco-com:service:LensControl:1#Iris")
    @RequestWrapper(localName = "Iris", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.Iris")
    @ResponseWrapper(localName = "IrisResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.IrisResponse")
    public void iris(
            @WebParam(name = "openClose", targetNamespace = "")
            long openClose
    );

    @WebMethod(operationName = "GetMag", action = "urn:schemas-pelco-com:service:LensControl:1#GetMag")
    @RequestWrapper(localName = "GetMag", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMag")
    @ResponseWrapper(localName = "GetMagResponse", targetNamespace = "urn:schemas-pelco-com:service:LensControl:1", className = "com.cmos.ipa.service.video_surveillance.lensControlV1.GetMagResponse")
    @WebResult(name = "magnification", targetNamespace = "")
    public long getMag();
}
