package com.cmos.ipa.service.video_surveillance.lensControlV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:18.158+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "LensControl", 
                  wsdlLocation = "file:wsdl/LensControlV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:LensControl:1") 
public class LensControl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:LensControl:1", "LensControl");
    public final static QName LensControl = new QName("urn:schemas-pelco-com:service:LensControl:1", "LensControl");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/LensControlV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LensControl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/LensControlV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LensControl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LensControl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LensControl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LensControl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LensControl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LensControl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LensControlPortType
     */
    @WebEndpoint(name = "LensControl")
    public LensControlPortType getLensControl() {
        return super.getPort(LensControl, LensControlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LensControlPortType
     */
    @WebEndpoint(name = "LensControl")
    public LensControlPortType getLensControl(WebServiceFeature... features) {
        return super.getPort(LensControl, LensControlPortType.class, features);
    }

}
