package com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The AlarmArrayConfiguration service allows multiple alarms to be evented from a single service. Each alarm in the service is individually identified by an alarmID, which in essence is an index into the array. Each AlarmArrayConfiguration service should be wrapped up by an AlarmArray device, much like an AlarmControl service is wrapped up by an Alarm device.
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:17:55.053+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "AlarmArrayConfiguration", 
                  wsdlLocation = "file:wsdl/AlarmArrayConfigurationV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1") 
public class AlarmArrayConfiguration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", "AlarmArrayConfiguration");
    public final static QName AlarmArrayConfiguration = new QName("urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", "AlarmArrayConfiguration");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/AlarmArrayConfigurationV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlarmArrayConfiguration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/AlarmArrayConfigurationV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlarmArrayConfiguration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlarmArrayConfiguration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlarmArrayConfiguration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlarmArrayConfiguration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AlarmArrayConfiguration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AlarmArrayConfiguration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AlarmArrayConfigurationPortType
     */
    @WebEndpoint(name = "AlarmArrayConfiguration")
    public AlarmArrayConfigurationPortType getAlarmArrayConfiguration() {
        return super.getPort(AlarmArrayConfiguration, AlarmArrayConfigurationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlarmArrayConfigurationPortType
     */
    @WebEndpoint(name = "AlarmArrayConfiguration")
    public AlarmArrayConfigurationPortType getAlarmArrayConfiguration(WebServiceFeature... features) {
        return super.getPort(AlarmArrayConfiguration, AlarmArrayConfigurationPortType.class, features);
    }

}
