package com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:17:55.041+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", name = "AlarmArrayConfigurationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface AlarmArrayConfigurationPortType {

    /**
     * Sets the configuration of the alarm input.
     */
    @WebMethod(operationName = "SetConfiguration", action = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#SetConfiguration")
    @RequestWrapper(localName = "SetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.SetConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.SetConfigurationResponse")
    public void setConfiguration(
            @WebParam(name = "alarmID", targetNamespace = "")
            int alarmID,
            @WebParam(name = "alarmConfig", targetNamespace = "")
            AlarmConfig alarmConfig
    );

    /**
     * Returns the number of alarms contained in the alarm array.
     */
    @WebMethod(operationName = "GetArraySize", action = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#GetArraySize")
    @RequestWrapper(localName = "GetArraySize", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.GetArraySize")
    @ResponseWrapper(localName = "GetArraySizeResponse", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.GetArraySizeResponse")
    @WebResult(name = "size", targetNamespace = "")
    public int getArraySize();

    /**
     * Returns the alarm input to the default configuration state.
     */
    @WebMethod(operationName = "ResetConfiguration", action = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#ResetConfiguration")
    @RequestWrapper(localName = "ResetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.ResetConfiguration")
    @ResponseWrapper(localName = "ResetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.ResetConfigurationResponse")
    public void resetConfiguration(
            @WebParam(name = "alarmID", targetNamespace = "")
            int alarmID
    );

    @WebMethod(operationName = "GetAlarmStates", action = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#GetAlarmStates")
    @RequestWrapper(localName = "GetAlarmStates", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.GetAlarmStates")
    @ResponseWrapper(localName = "GetAlarmStatesResponse", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.GetAlarmStatesResponse")
    @WebResult(name = "alarmStates", targetNamespace = "")
    public AlarmStates getAlarmStates();

    /**
     * Sets the current state of the alarm input indicated by alarmed to either 1 or 0.
     */
    @WebMethod(operationName = "SetAlarmState", action = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#SetAlarmState")
    @RequestWrapper(localName = "SetAlarmState", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.SetAlarmState")
    @ResponseWrapper(localName = "SetAlarmStateResponse", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.SetAlarmStateResponse")
    public void setAlarmState(
            @WebParam(name = "alarmID", targetNamespace = "")
            int alarmID,
            @WebParam(name = "alarmState", targetNamespace = "")
            int alarmState
    );

    /**
     * Get the configuration of the alarm input.
     */
    @WebMethod(operationName = "GetConfiguration", action = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.alarmArrayConfigurationV1.GetConfigurationResponse")
    @WebResult(name = "alarmConfig", targetNamespace = "")
    public AlarmConfig getConfiguration(
            @WebParam(name = "alarmID", targetNamespace = "")
            int alarmID
    );
}
