package com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:29.365+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "PelcoConfiguration", 
                  wsdlLocation = "file:wsdl/PelcoConfigurationV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1") 
public class PelcoConfiguration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:PelcoConfiguration:1", "PelcoConfiguration");
    public final static QName PelcoConfiguration = new QName("urn:schemas-pelco-com:service:PelcoConfiguration:1", "PelcoConfiguration");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/PelcoConfigurationV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PelcoConfiguration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/PelcoConfigurationV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PelcoConfiguration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PelcoConfiguration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PelcoConfiguration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PelcoConfiguration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PelcoConfiguration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PelcoConfiguration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PelcoConfigurationPortType
     */
    @WebEndpoint(name = "PelcoConfiguration")
    public PelcoConfigurationPortType getPelcoConfiguration() {
        return super.getPort(PelcoConfiguration, PelcoConfigurationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PelcoConfigurationPortType
     */
    @WebEndpoint(name = "PelcoConfiguration")
    public PelcoConfigurationPortType getPelcoConfiguration(WebServiceFeature... features) {
        return super.getPort(PelcoConfiguration, PelcoConfigurationPortType.class, features);
    }

}
