
package com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:29.264+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class PelcoConfigurationPortType_PelcoConfiguration_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:PelcoConfiguration:1", "PelcoConfiguration");

    private PelcoConfigurationPortType_PelcoConfiguration_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PelcoConfiguration.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PelcoConfiguration ss = new PelcoConfiguration(wsdlURL, SERVICE_NAME);
        PelcoConfigurationPortType port = ss.getPelcoConfiguration();  
        
        {
        System.out.println("Invoking getModelName...");
        String _getModelName__return = port.getModelName();
        System.out.println("getModelName.result=" + _getModelName__return);


        }
        {
        System.out.println("Invoking getModelNumber...");
        String _getModelNumber__return = port.getModelNumber();
        System.out.println("getModelNumber.result=" + _getModelNumber__return);


        }
        {
        System.out.println("Invoking getLocation...");
        String _getLocation__return = port.getLocation();
        System.out.println("getLocation.result=" + _getLocation__return);


        }
        {
        System.out.println("Invoking getConfiguration...");
        PelcoConfig _getConfiguration__return = port.getConfiguration();
        System.out.println("getConfiguration.result=" + _getConfiguration__return);


        }
        {
        System.out.println("Invoking isRegistered...");
        int _isRegistered__return = port.isRegistered();
        System.out.println("isRegistered.result=" + _isRegistered__return);


        }

        System.exit(0);
    }

}
