package com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:29.354+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", name = "PelcoConfigurationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PelcoConfigurationPortType {

    /**
     * Returns the device's model name.
     * 			
     */
    @WebMethod(operationName = "GetModelName", action = "urn:schemas-pelco-com:service:PelcoConfiguration:1#GetModelName")
    @RequestWrapper(localName = "GetModelName", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetModelName")
    @ResponseWrapper(localName = "GetModelNameResponse", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetModelNameResponse")
    @WebResult(name = "modelName", targetNamespace = "")
    public String getModelName();

    /**
     * Returns the device's model number.
     * 			
     */
    @WebMethod(operationName = "GetModelNumber", action = "urn:schemas-pelco-com:service:PelcoConfiguration:1#GetModelNumber")
    @RequestWrapper(localName = "GetModelNumber", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetModelNumber")
    @ResponseWrapper(localName = "GetModelNumberResponse", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetModelNumberResponse")
    @WebResult(name = "modelNumber", targetNamespace = "")
    public String getModelNumber();

    /**
     * Returns the URL of the Upnp device description file for the device.
     * 			
     */
    @WebMethod(operationName = "GetLocation", action = "urn:schemas-pelco-com:service:PelcoConfiguration:1#GetLocation")
    @RequestWrapper(localName = "GetLocation", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetLocation")
    @ResponseWrapper(localName = "GetLocationResponse", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetLocationResponse")
    @WebResult(name = "location", targetNamespace = "")
    public String getLocation();

    /**
     * Returns the current configuration state of the device.
     * 				
     * 				
     * 			
     */
    @WebMethod(operationName = "GetConfiguration", action = "urn:schemas-pelco-com:service:PelcoConfiguration:1#GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.GetConfigurationResponse")
    @WebResult(name = "pelcoConfig", targetNamespace = "")
    public PelcoConfig getConfiguration();

    /**
     * Indicates whether or not the device has registered with the
     * 				System Manager.
     * 			
     */
    @WebMethod(operationName = "IsRegistered", action = "urn:schemas-pelco-com:service:PelcoConfiguration:1#IsRegistered")
    @RequestWrapper(localName = "IsRegistered", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.IsRegistered")
    @ResponseWrapper(localName = "IsRegisteredResponse", targetNamespace = "urn:schemas-pelco-com:service:PelcoConfiguration:1", className = "com.cmos.ipa.service.video_surveillance.pelcoConfigurationV1.IsRegisteredResponse")
    @WebResult(name = "isRegistered", targetNamespace = "")
    public int isRegistered();
}
