
package com.cmos.ipa.service.access_control.aicThird;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-20T09:51:20.459+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class SmsNotificationPort_SmsNotificationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.sdp.com.cn/wsdl/sag/sms/notification/v2_1/interface", "SmsNotificationService");

    private SmsNotificationPort_SmsNotificationPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SmsNotificationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmsNotificationService ss = new SmsNotificationService(wsdlURL, SERVICE_NAME);
        SmsNotificationPort port = ss.getSmsNotificationPort();  
        
        {
        System.out.println("Invoking deleteAccessGroupItem...");
        String _deleteAccessGroupItem_guid = "";
        int _deleteAccessGroupItem__return = port.deleteAccessGroupItem(_deleteAccessGroupItem_guid);
        System.out.println("deleteAccessGroupItem.result=" + _deleteAccessGroupItem__return);


        }
        {
        System.out.println("Invoking editElevatorGroupItem...");
        String _editElevatorGroupItem_guid = "";
        String _editElevatorGroupItem_readerGuid = "";
        String _editElevatorGroupItem_outputGuid = "";
        String _editElevatorGroupItem_extParam = "";
        int _editElevatorGroupItem__return = port.editElevatorGroupItem(_editElevatorGroupItem_guid, _editElevatorGroupItem_readerGuid, _editElevatorGroupItem_outputGuid, _editElevatorGroupItem_extParam);
        System.out.println("editElevatorGroupItem.result=" + _editElevatorGroupItem__return);


        }
        {
        System.out.println("Invoking editSchedulesItem...");
        String _editSchedulesItem_guid = "";
        String _editSchedulesItem_schedulesGuid = "";
        int _editSchedulesItem_day = 0;
        int _editSchedulesItem_intervalID = 0;
        String _editSchedulesItem_begintime = "";
        String _editSchedulesItem_endtime = "";
        String _editSchedulesItem_extParam = "";
        int _editSchedulesItem__return = port.editSchedulesItem(_editSchedulesItem_guid, _editSchedulesItem_schedulesGuid, _editSchedulesItem_day, _editSchedulesItem_intervalID, _editSchedulesItem_begintime, _editSchedulesItem_endtime, _editSchedulesItem_extParam);
        System.out.println("editSchedulesItem.result=" + _editSchedulesItem__return);


        }
        {
        System.out.println("Invoking deleteDepart...");
        String _deleteDepart_guid = "";
        int _deleteDepart__return = port.deleteDepart(_deleteDepart_guid);
        System.out.println("deleteDepart.result=" + _deleteDepart__return);


        }
        {
        System.out.println("Invoking deleteAccessGroup...");
        String _deleteAccessGroup_guid = "";
        int _deleteAccessGroup__return = port.deleteAccessGroup(_deleteAccessGroup_guid);
        System.out.println("deleteAccessGroup.result=" + _deleteAccessGroup__return);


        }
        {
        System.out.println("Invoking editAccessGroupItem...");
        String _editAccessGroupItem_guid = "";
        String _editAccessGroupItem_doorGroupGuid = "";
        String _editAccessGroupItem_schedulesGuid = "";
        String _editAccessGroupItem_extParam = "";
        int _editAccessGroupItem__return = port.editAccessGroupItem(_editAccessGroupItem_guid, _editAccessGroupItem_doorGroupGuid, _editAccessGroupItem_schedulesGuid, _editAccessGroupItem_extParam);
        System.out.println("editAccessGroupItem.result=" + _editAccessGroupItem__return);


        }
        {
        System.out.println("Invoking addAccessGroup...");
        String _addAccessGroup_guid = "";
        String _addAccessGroup_name = "";
        String _addAccessGroup_extParam = "";
        int _addAccessGroup__return = port.addAccessGroup(_addAccessGroup_guid, _addAccessGroup_name, _addAccessGroup_extParam);
        System.out.println("addAccessGroup.result=" + _addAccessGroup__return);


        }
        {
        System.out.println("Invoking addSchedules...");
        String _addSchedules_guid = "";
        String _addSchedules_name = "";
        String _addSchedules_extParam = "";
        int _addSchedules__return = port.addSchedules(_addSchedules_guid, _addSchedules_name, _addSchedules_extParam);
        System.out.println("addSchedules.result=" + _addSchedules__return);


        }
        {
        System.out.println("Invoking query...");
        int _query_type = 0;
        String _query__return = port.query(_query_type);
        System.out.println("query.result=" + _query__return);


        }
        {
        System.out.println("Invoking addDepart...");
        String _addDepart_guid = "";
        String _addDepart_code = "";
        String _addDepart_name = "";
        String _addDepart_parentCode = "";
        String _addDepart_extParam = "";
        int _addDepart__return = port.addDepart(_addDepart_guid, _addDepart_code, _addDepart_name, _addDepart_parentCode, _addDepart_extParam);
        System.out.println("addDepart.result=" + _addDepart__return);


        }
        {
        System.out.println("Invoking queryEmployeeBalance...");
        String _queryEmployeeBalance_peCode = "";
        int _queryEmployeeBalance_bnCode = 0;
        String _queryEmployeeBalance__return = port.queryEmployeeBalance(_queryEmployeeBalance_peCode, _queryEmployeeBalance_bnCode);
        System.out.println("queryEmployeeBalance.result=" + _queryEmployeeBalance__return);


        }
        {
        System.out.println("Invoking addHolidayItem...");
        String _addHolidayItem_guid = "";
        String _addHolidayItem_holidayGuid = "";
        String _addHolidayItem_holidayTime = "";
        String _addHolidayItem_extParam = "";
        int _addHolidayItem__return = port.addHolidayItem(_addHolidayItem_guid, _addHolidayItem_holidayGuid, _addHolidayItem_holidayTime, _addHolidayItem_extParam);
        System.out.println("addHolidayItem.result=" + _addHolidayItem__return);


        }
        {
        System.out.println("Invoking deleteElevatorGroup...");
        String _deleteElevatorGroup_guid = "";
        int _deleteElevatorGroup__return = port.deleteElevatorGroup(_deleteElevatorGroup_guid);
        System.out.println("deleteElevatorGroup.result=" + _deleteElevatorGroup__return);


        }
        {
        System.out.println("Invoking addElevatorGroup...");
        String _addElevatorGroup_guid = "";
        String _addElevatorGroup_name = "";
        String _addElevatorGroup_extParam = "";
        int _addElevatorGroup__return = port.addElevatorGroup(_addElevatorGroup_guid, _addElevatorGroup_name, _addElevatorGroup_extParam);
        System.out.println("addElevatorGroup.result=" + _addElevatorGroup__return);


        }
        {
        System.out.println("Invoking addDoorGroup...");
        String _addDoorGroup_guid = "";
        String _addDoorGroup_name = "";
        String _addDoorGroup_extParam = "";
        int _addDoorGroup__return = port.addDoorGroup(_addDoorGroup_guid, _addDoorGroup_name, _addDoorGroup_extParam);
        System.out.println("addDoorGroup.result=" + _addDoorGroup__return);


        }
        {
        System.out.println("Invoking addHolidays...");
        String _addHolidays_guid = "";
        String _addHolidays_name = "";
        String _addHolidays_extParam = "";
        int _addHolidays__return = port.addHolidays(_addHolidays_guid, _addHolidays_name, _addHolidays_extParam);
        System.out.println("addHolidays.result=" + _addHolidays__return);


        }
        {
        System.out.println("Invoking downLoadConfig...");
        int _downLoadConfig_accessGroup = 0;
        int _downLoadConfig_doorGroup = 0;
        int _downLoadConfig_schedules = 0;
        int _downLoadConfig_elevatorGroup = 0;
        int _downLoadConfig_holiday = 0;
        String _downLoadConfig_extParam = "";
        int _downLoadConfig__return = port.downLoadConfig(_downLoadConfig_accessGroup, _downLoadConfig_doorGroup, _downLoadConfig_schedules, _downLoadConfig_elevatorGroup, _downLoadConfig_holiday, _downLoadConfig_extParam);
        System.out.println("downLoadConfig.result=" + _downLoadConfig__return);


        }
        {
        System.out.println("Invoking editSchedules...");
        String _editSchedules_guid = "";
        String _editSchedules_name = "";
        String _editSchedules_extParam = "";
        int _editSchedules__return = port.editSchedules(_editSchedules_guid, _editSchedules_name, _editSchedules_extParam);
        System.out.println("editSchedules.result=" + _editSchedules__return);


        }
        {
        System.out.println("Invoking cmdOutput...");
        String _cmdOutput_ipAddr = "";
        int _cmdOutput_target = 0;
        int _cmdOutput_functioncode = 0;
        int _cmdOutput_state = 0;
        int _cmdOutput__return = port.cmdOutput(_cmdOutput_ipAddr, _cmdOutput_target, _cmdOutput_functioncode, _cmdOutput_state);
        System.out.println("cmdOutput.result=" + _cmdOutput__return);


        }
        {
        System.out.println("Invoking deleteHolidayItem...");
        String _deleteHolidayItem_guid = "";
        int _deleteHolidayItem__return = port.deleteHolidayItem(_deleteHolidayItem_guid);
        System.out.println("deleteHolidayItem.result=" + _deleteHolidayItem__return);


        }
        {
        System.out.println("Invoking deleteDoorGroup...");
        String _deleteDoorGroup_guid = "";
        int _deleteDoorGroup__return = port.deleteDoorGroup(_deleteDoorGroup_guid);
        System.out.println("deleteDoorGroup.result=" + _deleteDoorGroup__return);


        }
        {
        System.out.println("Invoking addCredential...");
        String _addCredential_peopleGuid = "";
        String _addCredential_guid = "";
        String _addCredential_beginDatetime = "";
        String _addCredential_endDatetime = "";
        int _addCredential_wiegand = 0;
        int _addCredential_accessType = 0;
        String _addCredential_cardCode = "";
        String _addCredential_passWord = "";
        String _addCredential_accessGroup1ID = "";
        String _addCredential_accessGroup2ID = "";
        String _addCredential_accessGroup3ID = "";
        String _addCredential_accessGroup4ID = "";
        String _addCredential_accessGroup5ID = "";
        String _addCredential_accessGroup6ID = "";
        String _addCredential_accessGroup7ID = "";
        String _addCredential_accessGroup8ID = "";
        int _addCredential_passbackExempt = 0;
        int _addCredential_extendedAccess = 0;
        int _addCredential_pinCmds = 0;
        int _addCredential_pinExempt = 0;
        String _addCredential_inScheduleElevatorGroup = "";
        String _addCredential_outScheduleElevatorGroup = "";
        String _addCredential_extParam = "";
        int _addCredential__return = port.addCredential(_addCredential_peopleGuid, _addCredential_guid, _addCredential_beginDatetime, _addCredential_endDatetime, _addCredential_wiegand, _addCredential_accessType, _addCredential_cardCode, _addCredential_passWord, _addCredential_accessGroup1ID, _addCredential_accessGroup2ID, _addCredential_accessGroup3ID, _addCredential_accessGroup4ID, _addCredential_accessGroup5ID, _addCredential_accessGroup6ID, _addCredential_accessGroup7ID, _addCredential_accessGroup8ID, _addCredential_passbackExempt, _addCredential_extendedAccess, _addCredential_pinCmds, _addCredential_pinExempt, _addCredential_inScheduleElevatorGroup, _addCredential_outScheduleElevatorGroup, _addCredential_extParam);
        System.out.println("addCredential.result=" + _addCredential__return);


        }
        {
        System.out.println("Invoking deleteSchedules...");
        String _deleteSchedules_guid = "";
        int _deleteSchedules__return = port.deleteSchedules(_deleteSchedules_guid);
        System.out.println("deleteSchedules.result=" + _deleteSchedules__return);


        }
        {
        System.out.println("Invoking editElevatorGroup...");
        String _editElevatorGroup_guid = "";
        String _editElevatorGroup_name = "";
        String _editElevatorGroup_extParam = "";
        int _editElevatorGroup__return = port.editElevatorGroup(_editElevatorGroup_guid, _editElevatorGroup_name, _editElevatorGroup_extParam);
        System.out.println("editElevatorGroup.result=" + _editElevatorGroup__return);


        }
        {
        System.out.println("Invoking editHolidayItem...");
        String _editHolidayItem_guid = "";
        String _editHolidayItem_holidayGuid = "";
        String _editHolidayItem_holidayTime = "";
        String _editHolidayItem_extParam = "";
        int _editHolidayItem__return = port.editHolidayItem(_editHolidayItem_guid, _editHolidayItem_holidayGuid, _editHolidayItem_holidayTime, _editHolidayItem_extParam);
        System.out.println("editHolidayItem.result=" + _editHolidayItem__return);


        }
        {
        System.out.println("Invoking addElevatorGroupItem...");
        String _addElevatorGroupItem_guid = "";
        String _addElevatorGroupItem_elevatorGroupGuid = "";
        String _addElevatorGroupItem_readerGuid = "";
        String _addElevatorGroupItem_outputGuid = "";
        String _addElevatorGroupItem_extParam = "";
        int _addElevatorGroupItem__return = port.addElevatorGroupItem(_addElevatorGroupItem_guid, _addElevatorGroupItem_elevatorGroupGuid, _addElevatorGroupItem_readerGuid, _addElevatorGroupItem_outputGuid, _addElevatorGroupItem_extParam);
        System.out.println("addElevatorGroupItem.result=" + _addElevatorGroupItem__return);


        }
        {
        System.out.println("Invoking editCredential...");
        String _editCredential_peopleGuid = "";
        String _editCredential_guid = "";
        String _editCredential_beginDatetime = "";
        String _editCredential_endDatetime = "";
        int _editCredential_wiegand = 0;
        int _editCredential_accessType = 0;
        String _editCredential_cardCode = "";
        String _editCredential_passWord = "";
        String _editCredential_accessGroup1ID = "";
        String _editCredential_accessGroup2ID = "";
        String _editCredential_accessGroup3ID = "";
        String _editCredential_accessGroup4ID = "";
        String _editCredential_accessGroup5ID = "";
        String _editCredential_accessGroup6ID = "";
        String _editCredential_accessGroup7ID = "";
        String _editCredential_accessGroup8ID = "";
        int _editCredential_passbackExempt = 0;
        int _editCredential_extendedAccess = 0;
        int _editCredential_pinCmds = 0;
        int _editCredential_pinExempt = 0;
        String _editCredential_inScheduleElevatorGroup = "";
        String _editCredential_outScheduleElevatorGroup = "";
        String _editCredential_extParam = "";
        int _editCredential__return = port.editCredential(_editCredential_peopleGuid, _editCredential_guid, _editCredential_beginDatetime, _editCredential_endDatetime, _editCredential_wiegand, _editCredential_accessType, _editCredential_cardCode, _editCredential_passWord, _editCredential_accessGroup1ID, _editCredential_accessGroup2ID, _editCredential_accessGroup3ID, _editCredential_accessGroup4ID, _editCredential_accessGroup5ID, _editCredential_accessGroup6ID, _editCredential_accessGroup7ID, _editCredential_accessGroup8ID, _editCredential_passbackExempt, _editCredential_extendedAccess, _editCredential_pinCmds, _editCredential_pinExempt, _editCredential_inScheduleElevatorGroup, _editCredential_outScheduleElevatorGroup, _editCredential_extParam);
        System.out.println("editCredential.result=" + _editCredential__return);


        }
        {
        System.out.println("Invoking editPeople...");
        String _editPeople_guid = "";
        String _editPeople_code = "";
        String _editPeople_name = "";
        int _editPeople_sex = 0;
        String _editPeople_departCode = "";
        String _editPeople_extParam = "";
        int _editPeople__return = port.editPeople(_editPeople_guid, _editPeople_code, _editPeople_name, _editPeople_sex, _editPeople_departCode, _editPeople_extParam);
        System.out.println("editPeople.result=" + _editPeople__return);


        }
        {
        System.out.println("Invoking deleteElevatorGroupItem...");
        String _deleteElevatorGroupItem_guid = "";
        int _deleteElevatorGroupItem__return = port.deleteElevatorGroupItem(_deleteElevatorGroupItem_guid);
        System.out.println("deleteElevatorGroupItem.result=" + _deleteElevatorGroupItem__return);


        }
        {
        System.out.println("Invoking editDoorGroupItem...");
        String _editDoorGroupItem_guid = "";
        String _editDoorGroupItem_readGuid = "";
        String _editDoorGroupItem_extParam = "";
        int _editDoorGroupItem__return = port.editDoorGroupItem(_editDoorGroupItem_guid, _editDoorGroupItem_readGuid, _editDoorGroupItem_extParam);
        System.out.println("editDoorGroupItem.result=" + _editDoorGroupItem__return);


        }
        {
        System.out.println("Invoking addSchedulesItem...");
        String _addSchedulesItem_guid = "";
        String _addSchedulesItem_schedulesGuid = "";
        int _addSchedulesItem_day = 0;
        int _addSchedulesItem_intervalID = 0;
        String _addSchedulesItem_begintime = "";
        String _addSchedulesItem_endtime = "";
        String _addSchedulesItem_extParam = "";
        int _addSchedulesItem__return = port.addSchedulesItem(_addSchedulesItem_guid, _addSchedulesItem_schedulesGuid, _addSchedulesItem_day, _addSchedulesItem_intervalID, _addSchedulesItem_begintime, _addSchedulesItem_endtime, _addSchedulesItem_extParam);
        System.out.println("addSchedulesItem.result=" + _addSchedulesItem__return);


        }
        {
        System.out.println("Invoking editHolidays...");
        String _editHolidays_guid = "";
        String _editHolidays_name = "";
        String _editHolidays_extParam = "";
        int _editHolidays__return = port.editHolidays(_editHolidays_guid, _editHolidays_name, _editHolidays_extParam);
        System.out.println("editHolidays.result=" + _editHolidays__return);


        }
        {
        System.out.println("Invoking editAccessGroup...");
        String _editAccessGroup_guid = "";
        String _editAccessGroup_name = "";
        String _editAccessGroup_extParam = "";
        int _editAccessGroup__return = port.editAccessGroup(_editAccessGroup_guid, _editAccessGroup_name, _editAccessGroup_extParam);
        System.out.println("editAccessGroup.result=" + _editAccessGroup__return);


        }
        {
        System.out.println("Invoking deleteCredential...");
        String _deleteCredential_guid = "";
        int _deleteCredential__return = port.deleteCredential(_deleteCredential_guid);
        System.out.println("deleteCredential.result=" + _deleteCredential__return);


        }
        {
        System.out.println("Invoking editDepart...");
        String _editDepart_guid = "";
        String _editDepart_code = "";
        String _editDepart_name = "";
        String _editDepart_parentCode = "";
        String _editDepart_extParam = "";
        int _editDepart__return = port.editDepart(_editDepart_guid, _editDepart_code, _editDepart_name, _editDepart_parentCode, _editDepart_extParam);
        System.out.println("editDepart.result=" + _editDepart__return);


        }
        {
        System.out.println("Invoking addDoorGroupItem...");
        String _addDoorGroupItem_guid = "";
        String _addDoorGroupItem_doorGroupGuid = "";
        String _addDoorGroupItem_readGuid = "";
        String _addDoorGroupItem_extParam = "";
        int _addDoorGroupItem__return = port.addDoorGroupItem(_addDoorGroupItem_guid, _addDoorGroupItem_doorGroupGuid, _addDoorGroupItem_readGuid, _addDoorGroupItem_extParam);
        System.out.println("addDoorGroupItem.result=" + _addDoorGroupItem__return);


        }
        {
        System.out.println("Invoking deleteSchedulesItem...");
        String _deleteSchedulesItem_guid = "";
        int _deleteSchedulesItem__return = port.deleteSchedulesItem(_deleteSchedulesItem_guid);
        System.out.println("deleteSchedulesItem.result=" + _deleteSchedulesItem__return);


        }
        {
        System.out.println("Invoking deleteHolidays...");
        String _deleteHolidays_guid = "";
        int _deleteHolidays__return = port.deleteHolidays(_deleteHolidays_guid);
        System.out.println("deleteHolidays.result=" + _deleteHolidays__return);


        }
        {
        System.out.println("Invoking querySocketMessage...");
        int _querySocketMessage_startID = 0;
        int _querySocketMessage_endID = 0;
        String _querySocketMessage__return = port.querySocketMessage(_querySocketMessage_startID, _querySocketMessage_endID);
        System.out.println("querySocketMessage.result=" + _querySocketMessage__return);


        }
        {
        System.out.println("Invoking addPeople...");
        String _addPeople_guid = "";
        String _addPeople_code = "";
        String _addPeople_name = "";
        int _addPeople_sex = 0;
        String _addPeople_departCode = "";
        String _addPeople_extParam = "";
        int _addPeople__return = port.addPeople(_addPeople_guid, _addPeople_code, _addPeople_name, _addPeople_sex, _addPeople_departCode, _addPeople_extParam);
        System.out.println("addPeople.result=" + _addPeople__return);


        }
        {
        System.out.println("Invoking deleteDoorGroupItem...");
        String _deleteDoorGroupItem_guid = "";
        int _deleteDoorGroupItem__return = port.deleteDoorGroupItem(_deleteDoorGroupItem_guid);
        System.out.println("deleteDoorGroupItem.result=" + _deleteDoorGroupItem__return);


        }
        {
        System.out.println("Invoking deletePeople...");
        String _deletePeople_guid = "";
        int _deletePeople__return = port.deletePeople(_deletePeople_guid);
        System.out.println("deletePeople.result=" + _deletePeople__return);


        }
        {
        System.out.println("Invoking editDoorGroup...");
        String _editDoorGroup_guid = "";
        String _editDoorGroup_name = "";
        String _editDoorGroup_extParam = "";
        int _editDoorGroup__return = port.editDoorGroup(_editDoorGroup_guid, _editDoorGroup_name, _editDoorGroup_extParam);
        System.out.println("editDoorGroup.result=" + _editDoorGroup__return);


        }
        {
        System.out.println("Invoking addAccessGroupItem...");
        String _addAccessGroupItem_guid = "";
        String _addAccessGroupItem_accessGroupGuid = "";
        String _addAccessGroupItem_doorGroupGuid = "";
        String _addAccessGroupItem_schedulesGuid = "";
        String _addAccessGroupItem_extParam = "";
        int _addAccessGroupItem__return = port.addAccessGroupItem(_addAccessGroupItem_guid, _addAccessGroupItem_accessGroupGuid, _addAccessGroupItem_doorGroupGuid, _addAccessGroupItem_schedulesGuid, _addAccessGroupItem_extParam);
        System.out.println("addAccessGroupItem.result=" + _addAccessGroupItem__return);


        }

        System.exit(0);
    }

}
