package com.cmos.ipa.service.access_control.aicThird;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-20T09:51:20.564+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.sdp.com.cn/wsdl/sag/sms/notification/v2_1/interface", name = "SmsNotificationPort")
@XmlSeeAlso({ObjectFactory.class})
public interface SmsNotificationPort {

    @WebMethod(operationName = "DeleteAccessGroupItem")
    @RequestWrapper(localName = "DeleteAccessGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteAccessGroupItem")
    @ResponseWrapper(localName = "DeleteAccessGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteAccessGroupItemResponse")
    @WebResult(name = "DeleteAccessGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteAccessGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "EditElevatorGroupItem")
    @RequestWrapper(localName = "EditElevatorGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditElevatorGroupItem")
    @ResponseWrapper(localName = "EditElevatorGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditElevatorGroupItemResponse")
    @WebResult(name = "EditElevatorGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editElevatorGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "ReaderGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String readerGuid,
            @WebParam(name = "OutputGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String outputGuid,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditSchedulesItem")
    @RequestWrapper(localName = "EditSchedulesItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditSchedulesItem")
    @ResponseWrapper(localName = "EditSchedulesItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditSchedulesItemResponse")
    @WebResult(name = "EditSchedulesItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editSchedulesItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "SchedulesGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String schedulesGuid,
            @WebParam(name = "Day", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int day,
            @WebParam(name = "IntervalID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int intervalID,
            @WebParam(name = "Begintime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String begintime,
            @WebParam(name = "Endtime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String endtime,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteDepart")
    @RequestWrapper(localName = "DeleteDepart", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteDepart")
    @ResponseWrapper(localName = "DeleteDepartResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteDepartResponse")
    @WebResult(name = "DeleteDepartResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteDepart(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "DeleteAccessGroup")
    @RequestWrapper(localName = "DeleteAccessGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteAccessGroup")
    @ResponseWrapper(localName = "DeleteAccessGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteAccessGroupResponse")
    @WebResult(name = "DeleteAccessGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteAccessGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "EditAccessGroupItem")
    @RequestWrapper(localName = "EditAccessGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditAccessGroupItem")
    @ResponseWrapper(localName = "EditAccessGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditAccessGroupItemResponse")
    @WebResult(name = "EditAccessGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editAccessGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "DoorGroupGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String doorGroupGuid,
            @WebParam(name = "SchedulesGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String schedulesGuid,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddAccessGroup")
    @RequestWrapper(localName = "AddAccessGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddAccessGroup")
    @ResponseWrapper(localName = "AddAccessGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddAccessGroupResponse")
    @WebResult(name = "AddAccessGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addAccessGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddSchedules")
    @RequestWrapper(localName = "AddSchedules", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddSchedules")
    @ResponseWrapper(localName = "AddSchedulesResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddSchedulesResponse")
    @WebResult(name = "AddSchedulesResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addSchedules(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "Query")
    @RequestWrapper(localName = "Query", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.QueryResponse")
    @WebResult(name = "QueryResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public String query(
            @WebParam(name = "Type", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int type
    );

    @WebMethod(operationName = "AddDepart")
    @RequestWrapper(localName = "AddDepart", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddDepart")
    @ResponseWrapper(localName = "AddDepartResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddDepartResponse")
    @WebResult(name = "AddDepartResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addDepart(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Code", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String code,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "parentCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String parentCode,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "QueryEmployeeBalance")
    @RequestWrapper(localName = "QueryEmployeeBalance", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.QueryEmployeeBalance")
    @ResponseWrapper(localName = "QueryEmployeeBalanceResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.QueryEmployeeBalanceResponse")
    @WebResult(name = "QueryEmployeeBalanceResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public String queryEmployeeBalance(
            @WebParam(name = "PeCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String peCode,
            @WebParam(name = "BnCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int bnCode
    );

    @WebMethod(operationName = "AddHolidayItem")
    @RequestWrapper(localName = "AddHolidayItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddHolidayItem")
    @ResponseWrapper(localName = "AddHolidayItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddHolidayItemResponse")
    @WebResult(name = "AddHolidayItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addHolidayItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "HolidayGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String holidayGuid,
            @WebParam(name = "HolidayTime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String holidayTime,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteElevatorGroup")
    @RequestWrapper(localName = "DeleteElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteElevatorGroup")
    @ResponseWrapper(localName = "DeleteElevatorGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteElevatorGroupResponse")
    @WebResult(name = "DeleteElevatorGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteElevatorGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "AddElevatorGroup")
    @RequestWrapper(localName = "AddElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddElevatorGroup")
    @ResponseWrapper(localName = "AddElevatorGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddElevatorGroupResponse")
    @WebResult(name = "AddElevatorGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addElevatorGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddDoorGroup")
    @RequestWrapper(localName = "AddDoorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddDoorGroup")
    @ResponseWrapper(localName = "AddDoorGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddDoorGroupResponse")
    @WebResult(name = "AddDoorGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addDoorGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddHolidays")
    @RequestWrapper(localName = "AddHolidays", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddHolidays")
    @ResponseWrapper(localName = "AddHolidaysResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddHolidaysResponse")
    @WebResult(name = "AddHolidaysResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addHolidays(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DownLoadConfig")
    @RequestWrapper(localName = "DownLoadConfig", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DownLoadConfig")
    @ResponseWrapper(localName = "DownLoadConfigResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DownLoadConfigResponse")
    @WebResult(name = "DownLoadConfigResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int downLoadConfig(
            @WebParam(name = "AccessGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int accessGroup,
            @WebParam(name = "DoorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int doorGroup,
            @WebParam(name = "Schedules", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int schedules,
            @WebParam(name = "ElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int elevatorGroup,
            @WebParam(name = "Holiday", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int holiday,
            @WebParam(name = "ExtParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditSchedules")
    @RequestWrapper(localName = "EditSchedules", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditSchedules")
    @ResponseWrapper(localName = "EditSchedulesResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditSchedulesResponse")
    @WebResult(name = "EditSchedulesResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editSchedules(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "CmdOutput")
    @RequestWrapper(localName = "CmdOutput", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.CmdOutput")
    @ResponseWrapper(localName = "CmdOutputResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.CmdOutputResponse")
    @WebResult(name = "CmdOutputResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int cmdOutput(
            @WebParam(name = "ipAddr", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String ipAddr,
            @WebParam(name = "target", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int target,
            @WebParam(name = "functioncode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int functioncode,
            @WebParam(name = "state", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int state
    );

    @WebMethod(operationName = "DeleteHolidayItem")
    @RequestWrapper(localName = "DeleteHolidayItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteHolidayItem")
    @ResponseWrapper(localName = "DeleteHolidayItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteHolidayItemResponse")
    @WebResult(name = "DeleteHolidayItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteHolidayItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "DeleteDoorGroup")
    @RequestWrapper(localName = "DeleteDoorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteDoorGroup")
    @ResponseWrapper(localName = "DeleteDoorGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteDoorGroupResponse")
    @WebResult(name = "DeleteDoorGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteDoorGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "AddCredential")
    @RequestWrapper(localName = "AddCredential", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddCredential")
    @ResponseWrapper(localName = "AddCredentialResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddCredentialResponse")
    @WebResult(name = "AddCredentialResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addCredential(
            @WebParam(name = "PeopleGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String peopleGuid,
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "BeginDatetime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String beginDatetime,
            @WebParam(name = "EndDatetime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String endDatetime,
            @WebParam(name = "Wiegand", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int wiegand,
            @WebParam(name = "AccessType", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int accessType,
            @WebParam(name = "CardCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String cardCode,
            @WebParam(name = "PassWord", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String passWord,
            @WebParam(name = "AccessGroup1ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup1ID,
            @WebParam(name = "AccessGroup2ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup2ID,
            @WebParam(name = "AccessGroup3ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup3ID,
            @WebParam(name = "AccessGroup4ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup4ID,
            @WebParam(name = "AccessGroup5ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup5ID,
            @WebParam(name = "AccessGroup6ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup6ID,
            @WebParam(name = "AccessGroup7ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup7ID,
            @WebParam(name = "AccessGroup8ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup8ID,
            @WebParam(name = "PassbackExempt", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int passbackExempt,
            @WebParam(name = "ExtendedAccess", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int extendedAccess,
            @WebParam(name = "PinCmds", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int pinCmds,
            @WebParam(name = "PinExempt", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int pinExempt,
            @WebParam(name = "InScheduleElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String inScheduleElevatorGroup,
            @WebParam(name = "OutScheduleElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String outScheduleElevatorGroup,
            @WebParam(name = "ExtParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteSchedules")
    @RequestWrapper(localName = "DeleteSchedules", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteSchedules")
    @ResponseWrapper(localName = "DeleteSchedulesResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteSchedulesResponse")
    @WebResult(name = "DeleteSchedulesResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteSchedules(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "EditElevatorGroup")
    @RequestWrapper(localName = "EditElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditElevatorGroup")
    @ResponseWrapper(localName = "EditElevatorGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditElevatorGroupResponse")
    @WebResult(name = "EditElevatorGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editElevatorGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditHolidayItem")
    @RequestWrapper(localName = "EditHolidayItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditHolidayItem")
    @ResponseWrapper(localName = "EditHolidayItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditHolidayItemResponse")
    @WebResult(name = "EditHolidayItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editHolidayItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "HolidayGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String holidayGuid,
            @WebParam(name = "HolidayTime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String holidayTime,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddElevatorGroupItem")
    @RequestWrapper(localName = "AddElevatorGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddElevatorGroupItem")
    @ResponseWrapper(localName = "AddElevatorGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddElevatorGroupItemResponse")
    @WebResult(name = "AddElevatorGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addElevatorGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "ElevatorGroupGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String elevatorGroupGuid,
            @WebParam(name = "ReaderGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String readerGuid,
            @WebParam(name = "OutputGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String outputGuid,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditCredential")
    @RequestWrapper(localName = "EditCredential", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditCredential")
    @ResponseWrapper(localName = "EditCredentialResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditCredentialResponse")
    @WebResult(name = "EditCredentialResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editCredential(
            @WebParam(name = "PeopleGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String peopleGuid,
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "BeginDatetime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String beginDatetime,
            @WebParam(name = "EndDatetime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String endDatetime,
            @WebParam(name = "Wiegand", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int wiegand,
            @WebParam(name = "AccessType", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int accessType,
            @WebParam(name = "CardCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String cardCode,
            @WebParam(name = "PassWord", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String passWord,
            @WebParam(name = "AccessGroup1ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup1ID,
            @WebParam(name = "AccessGroup2ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup2ID,
            @WebParam(name = "AccessGroup3ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup3ID,
            @WebParam(name = "AccessGroup4ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup4ID,
            @WebParam(name = "AccessGroup5ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup5ID,
            @WebParam(name = "AccessGroup6ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup6ID,
            @WebParam(name = "AccessGroup7ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup7ID,
            @WebParam(name = "AccessGroup8ID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroup8ID,
            @WebParam(name = "PassbackExempt", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int passbackExempt,
            @WebParam(name = "ExtendedAccess", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int extendedAccess,
            @WebParam(name = "PinCmds", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int pinCmds,
            @WebParam(name = "PinExempt", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int pinExempt,
            @WebParam(name = "InScheduleElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String inScheduleElevatorGroup,
            @WebParam(name = "OutScheduleElevatorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String outScheduleElevatorGroup,
            @WebParam(name = "ExtParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditPeople")
    @RequestWrapper(localName = "EditPeople", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditPeople")
    @ResponseWrapper(localName = "EditPeopleResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditPeopleResponse")
    @WebResult(name = "EditPeopleResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editPeople(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Code", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String code,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "Sex", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int sex,
            @WebParam(name = "DepartCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String departCode,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteElevatorGroupItem")
    @RequestWrapper(localName = "DeleteElevatorGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteElevatorGroupItem")
    @ResponseWrapper(localName = "DeleteElevatorGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteElevatorGroupItemResponse")
    @WebResult(name = "DeleteElevatorGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteElevatorGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "EditDoorGroupItem")
    @RequestWrapper(localName = "EditDoorGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditDoorGroupItem")
    @ResponseWrapper(localName = "EditDoorGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditDoorGroupItemResponse")
    @WebResult(name = "EditDoorGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editDoorGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "ReadGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String readGuid,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddSchedulesItem")
    @RequestWrapper(localName = "AddSchedulesItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddSchedulesItem")
    @ResponseWrapper(localName = "AddSchedulesItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddSchedulesItemResponse")
    @WebResult(name = "AddSchedulesItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addSchedulesItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "SchedulesGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String schedulesGuid,
            @WebParam(name = "Day", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int day,
            @WebParam(name = "IntervalID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int intervalID,
            @WebParam(name = "Begintime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String begintime,
            @WebParam(name = "Endtime", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String endtime,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditHolidays")
    @RequestWrapper(localName = "EditHolidays", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditHolidays")
    @ResponseWrapper(localName = "EditHolidaysResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditHolidaysResponse")
    @WebResult(name = "EditHolidaysResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editHolidays(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "EditAccessGroup")
    @RequestWrapper(localName = "EditAccessGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditAccessGroup")
    @ResponseWrapper(localName = "EditAccessGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditAccessGroupResponse")
    @WebResult(name = "EditAccessGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editAccessGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteCredential")
    @RequestWrapper(localName = "DeleteCredential", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteCredential")
    @ResponseWrapper(localName = "DeleteCredentialResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteCredentialResponse")
    @WebResult(name = "DeleteCredentialResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteCredential(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "EditDepart")
    @RequestWrapper(localName = "EditDepart", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditDepart")
    @ResponseWrapper(localName = "EditDepartResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditDepartResponse")
    @WebResult(name = "EditDepartResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editDepart(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Code", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String code,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "parentCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String parentCode,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddDoorGroupItem")
    @RequestWrapper(localName = "AddDoorGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddDoorGroupItem")
    @ResponseWrapper(localName = "AddDoorGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddDoorGroupItemResponse")
    @WebResult(name = "AddDoorGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addDoorGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "DoorGroupGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String doorGroupGuid,
            @WebParam(name = "ReadGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String readGuid,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteSchedulesItem")
    @RequestWrapper(localName = "DeleteSchedulesItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteSchedulesItem")
    @ResponseWrapper(localName = "DeleteSchedulesItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteSchedulesItemResponse")
    @WebResult(name = "DeleteSchedulesItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteSchedulesItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "DeleteHolidays")
    @RequestWrapper(localName = "DeleteHolidays", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteHolidays")
    @ResponseWrapper(localName = "DeleteHolidaysResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteHolidaysResponse")
    @WebResult(name = "DeleteHolidaysResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteHolidays(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "QuerySocketMessage")
    @RequestWrapper(localName = "QuerySocketMessage", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.QuerySocketMessage")
    @ResponseWrapper(localName = "QuerySocketMessageResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.QuerySocketMessageResponse")
    @WebResult(name = "QuerySocketMessageResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public String querySocketMessage(
            @WebParam(name = "StartID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int startID,
            @WebParam(name = "EndID", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int endID
    );

    @WebMethod(operationName = "AddPeople")
    @RequestWrapper(localName = "AddPeople", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddPeople")
    @ResponseWrapper(localName = "AddPeopleResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddPeopleResponse")
    @WebResult(name = "AddPeopleResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addPeople(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Code", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String code,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "Sex", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            int sex,
            @WebParam(name = "DepartCode", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String departCode,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "DeleteDoorGroupItem")
    @RequestWrapper(localName = "DeleteDoorGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteDoorGroupItem")
    @ResponseWrapper(localName = "DeleteDoorGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeleteDoorGroupItemResponse")
    @WebResult(name = "DeleteDoorGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deleteDoorGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "DeletePeople")
    @RequestWrapper(localName = "DeletePeople", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeletePeople")
    @ResponseWrapper(localName = "DeletePeopleResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.DeletePeopleResponse")
    @WebResult(name = "DeletePeopleResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int deletePeople(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid
    );

    @WebMethod(operationName = "EditDoorGroup")
    @RequestWrapper(localName = "EditDoorGroup", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditDoorGroup")
    @ResponseWrapper(localName = "EditDoorGroupResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.EditDoorGroupResponse")
    @WebResult(name = "EditDoorGroupResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int editDoorGroup(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "Name", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String name,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );

    @WebMethod(operationName = "AddAccessGroupItem")
    @RequestWrapper(localName = "AddAccessGroupItem", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddAccessGroupItem")
    @ResponseWrapper(localName = "AddAccessGroupItemResponse", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local", className = "com.cmos.ipa.service.access_control.aicThird.AddAccessGroupItemResponse")
    @WebResult(name = "AddAccessGroupItemResult", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
    public int addAccessGroupItem(
            @WebParam(name = "Guid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String guid,
            @WebParam(name = "AccessGroupGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String accessGroupGuid,
            @WebParam(name = "DoorGroupGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String doorGroupGuid,
            @WebParam(name = "SchedulesGuid", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String schedulesGuid,
            @WebParam(name = "extParam", targetNamespace = "http://www.sdp.com.cn/schema/sag/sms/notification/v2_1/local")
            String extParam
    );
}
