
package com.cmos.ipa.service.video_surveillance.motionDetectionV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:26.529+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class MotionDetectionPortType_MotionDetection_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:MotionDetection:1", "MotionDetection");

    private MotionDetectionPortType_MotionDetection_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MotionDetection.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MotionDetection ss = new MotionDetection(wsdlURL, SERVICE_NAME);
        MotionDetectionPortType port = ss.getMotionDetection();  
        
        {
        System.out.println("Invoking resetMDConfiguration...");
        port.resetMDConfiguration();


        }
        {
        System.out.println("Invoking setEnabled...");
        int _setEnabled_enabled = 0;
        Integer _setEnabled_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _setEnabled_asyncId = new javax.xml.ws.Holder<Integer>(_setEnabled_asyncIdVal);
        port.setEnabled(_setEnabled_enabled, _setEnabled_asyncId);

        System.out.println("setEnabled._setEnabled_asyncId=" + _setEnabled_asyncId.value);

        }
        {
        System.out.println("Invoking clearMDRegions...");
        Integer _clearMDRegions_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _clearMDRegions_asyncId = new javax.xml.ws.Holder<Integer>(_clearMDRegions_asyncIdVal);
        port.clearMDRegions(_clearMDRegions_asyncId);

        System.out.println("clearMDRegions._clearMDRegions_asyncId=" + _clearMDRegions_asyncId.value);

        }
        {
        System.out.println("Invoking getMDConfiguration...");
        MDConfig _getMDConfiguration__return = port.getMDConfiguration();
        System.out.println("getMDConfiguration.result=" + _getMDConfiguration__return);


        }
        {
        System.out.println("Invoking getMaxRegions...");
        Integer _getMaxRegions_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _getMaxRegions_asyncId = new javax.xml.ws.Holder<Integer>(_getMaxRegions_asyncIdVal);
        javax.xml.ws.Holder<Integer> _getMaxRegions_maxRegions = new javax.xml.ws.Holder<Integer>();
        port.getMaxRegions(_getMaxRegions_asyncId, _getMaxRegions_maxRegions);

        System.out.println("getMaxRegions._getMaxRegions_asyncId=" + _getMaxRegions_asyncId.value);
        System.out.println("getMaxRegions._getMaxRegions_maxRegions=" + _getMaxRegions_maxRegions.value);

        }
        {
        System.out.println("Invoking getAlarmState...");
        int _getAlarmState__return = port.getAlarmState();
        System.out.println("getAlarmState.result=" + _getAlarmState__return);


        }
        {
        System.out.println("Invoking getGridSize...");
        Integer _getGridSize_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _getGridSize_asyncId = new javax.xml.ws.Holder<Integer>(_getGridSize_asyncIdVal);
        javax.xml.ws.Holder<Integer> _getGridSize_rows = new javax.xml.ws.Holder<Integer>();
        javax.xml.ws.Holder<Integer> _getGridSize_columns = new javax.xml.ws.Holder<Integer>();
        port.getGridSize(_getGridSize_asyncId, _getGridSize_rows, _getGridSize_columns);

        System.out.println("getGridSize._getGridSize_asyncId=" + _getGridSize_asyncId.value);
        System.out.println("getGridSize._getGridSize_rows=" + _getGridSize_rows.value);
        System.out.println("getGridSize._getGridSize_columns=" + _getGridSize_columns.value);

        }
        {
        System.out.println("Invoking getEnabled...");
        Integer _getEnabled_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _getEnabled_asyncId = new javax.xml.ws.Holder<Integer>(_getEnabled_asyncIdVal);
        javax.xml.ws.Holder<Integer> _getEnabled_enabled = new javax.xml.ws.Holder<Integer>();
        port.getEnabled(_getEnabled_asyncId, _getEnabled_enabled);

        System.out.println("getEnabled._getEnabled_asyncId=" + _getEnabled_asyncId.value);
        System.out.println("getEnabled._getEnabled_enabled=" + _getEnabled_enabled.value);

        }
        {
        System.out.println("Invoking getMaxSensitivity...");
        Integer _getMaxSensitivity_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _getMaxSensitivity_asyncId = new javax.xml.ws.Holder<Integer>(_getMaxSensitivity_asyncIdVal);
        javax.xml.ws.Holder<Integer> _getMaxSensitivity_maxSensitivity = new javax.xml.ws.Holder<Integer>();
        port.getMaxSensitivity(_getMaxSensitivity_asyncId, _getMaxSensitivity_maxSensitivity);

        System.out.println("getMaxSensitivity._getMaxSensitivity_asyncId=" + _getMaxSensitivity_asyncId.value);
        System.out.println("getMaxSensitivity._getMaxSensitivity_maxSensitivity=" + _getMaxSensitivity_maxSensitivity.value);

        }
        {
        System.out.println("Invoking getMDRegions...");
        Integer _getMDRegions_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _getMDRegions_asyncId = new javax.xml.ws.Holder<Integer>(_getMDRegions_asyncIdVal);
        javax.xml.ws.Holder<MDRegionList> _getMDRegions_regionList = new javax.xml.ws.Holder<MDRegionList>();
        port.getMDRegions(_getMDRegions_asyncId, _getMDRegions_regionList);

        System.out.println("getMDRegions._getMDRegions_asyncId=" + _getMDRegions_asyncId.value);
        System.out.println("getMDRegions._getMDRegions_regionList=" + _getMDRegions_regionList.value);

        }
        {
        System.out.println("Invoking setMDRegions...");
        MDRegionList _setMDRegions_regionList = null;
        Integer _setMDRegions_asyncIdVal = null;
        javax.xml.ws.Holder<Integer> _setMDRegions_asyncId = new javax.xml.ws.Holder<Integer>(_setMDRegions_asyncIdVal);
        port.setMDRegions(_setMDRegions_regionList, _setMDRegions_asyncId);

        System.out.println("setMDRegions._setMDRegions_asyncId=" + _setMDRegions_asyncId.value);

        }
        {
        System.out.println("Invoking setMDConfiguration...");
        MDConfig _setMDConfiguration_mdConfig = null;
        port.setMDConfiguration(_setMDConfiguration_mdConfig);


        }

        System.exit(0);
    }

}
