package com.cmos.ipa.service.video_surveillance.motionDetectionV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This service allows clients to query and modify the service provider's current motion detection configuration, as well as providing a Pelco device's current motion detection status.
 * 		
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:26.655+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "MotionDetection", 
                  wsdlLocation = "file:wsdl/MotionDetectionV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1") 
public class MotionDetection extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:MotionDetection:1", "MotionDetection");
    public final static QName MotionDetection = new QName("urn:schemas-pelco-com:service:MotionDetection:1", "MotionDetection");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/MotionDetectionV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MotionDetection.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/MotionDetectionV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MotionDetection(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MotionDetection(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MotionDetection() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MotionDetection(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MotionDetection(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MotionDetection(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MotionDetectionPortType
     */
    @WebEndpoint(name = "MotionDetection")
    public MotionDetectionPortType getMotionDetection() {
        return super.getPort(MotionDetection, MotionDetectionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MotionDetectionPortType
     */
    @WebEndpoint(name = "MotionDetection")
    public MotionDetectionPortType getMotionDetection(WebServiceFeature... features) {
        return super.getPort(MotionDetection, MotionDetectionPortType.class, features);
    }

}
