package com.cmos.ipa.service.video_surveillance.motionDetectionV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:26.638+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", name = "MotionDetectionPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MotionDetectionPortType {

    /**
     * Resets the device's motion detection configuration.
     */
    @WebMethod(operationName = "ResetMDConfiguration", action = "urn:schemas-pelco-com:service:MotionDetection:1#ResetMDConfiguration")
    @RequestWrapper(localName = "ResetMDConfiguration", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.ResetMDConfiguration")
    @ResponseWrapper(localName = "ResetMDConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.ResetMDConfigurationResponse")
    public void resetMDConfiguration();

    /**
     * 
     * 				
     * 			
     */
    @WebMethod(operationName = "SetEnabled", action = "urn:schemas-pelco-com:service:MotionDetection:1#SetEnabled")
    @RequestWrapper(localName = "SetEnabled", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.SetEnabled")
    @ResponseWrapper(localName = "SetEnabledResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.SetEnabledResponse")
    public void setEnabled(
            @WebParam(name = "enabled", targetNamespace = "")
            int enabled,
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId
    );

    /**
     * Clears all detection regions currently associated with the motion detection grid.
     */
    @WebMethod(operationName = "ClearMDRegions", action = "urn:schemas-pelco-com:service:MotionDetection:1#ClearMDRegions")
    @RequestWrapper(localName = "ClearMDRegions", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.ClearMDRegions")
    @ResponseWrapper(localName = "ClearMDRegionsResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.ClearMDRegionsResponse")
    public void clearMDRegions(
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId
    );

    /**
     * Returns the current motion detection configuration.
     */
    @WebMethod(operationName = "GetMDConfiguration", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetMDConfiguration")
    @RequestWrapper(localName = "GetMDConfiguration", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMDConfiguration")
    @ResponseWrapper(localName = "GetMDConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMDConfigurationResponse")
    @WebResult(name = "mdConfig", targetNamespace = "")
    public MDConfig getMDConfiguration();

    /**
     * 
     * 				
     * 			
     */
    @WebMethod(operationName = "GetMaxRegions", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetMaxRegions")
    @RequestWrapper(localName = "GetMaxRegions", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMaxRegions")
    @ResponseWrapper(localName = "GetMaxRegionsResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMaxRegionsResponse")
    public void getMaxRegions(
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId,
            @WebParam(mode = WebParam.Mode.OUT, name = "maxRegions", targetNamespace = "")
            javax.xml.ws.Holder<Integer> maxRegions
    );

    /**
     * 
     * 				
     * 				
     * 			
     */
    @WebMethod(operationName = "GetAlarmState", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetAlarmState")
    @RequestWrapper(localName = "GetAlarmState", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetAlarmState")
    @ResponseWrapper(localName = "GetAlarmStateResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetAlarmStateResponse")
    @WebResult(name = "alarmState", targetNamespace = "")
    public int getAlarmState();

    /**
     * 
     * 				
     * 				
     * 			
     */
    @WebMethod(operationName = "GetGridSize", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetGridSize")
    @RequestWrapper(localName = "GetGridSize", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetGridSize")
    @ResponseWrapper(localName = "GetGridSizeResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetGridSizeResponse")
    public void getGridSize(
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId,
            @WebParam(mode = WebParam.Mode.OUT, name = "rows", targetNamespace = "")
            javax.xml.ws.Holder<Integer> rows,
            @WebParam(mode = WebParam.Mode.OUT, name = "columns", targetNamespace = "")
            javax.xml.ws.Holder<Integer> columns
    );

    /**
     * 
     * 				
     * 			
     */
    @WebMethod(operationName = "GetEnabled", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetEnabled")
    @RequestWrapper(localName = "GetEnabled", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetEnabled")
    @ResponseWrapper(localName = "GetEnabledResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetEnabledResponse")
    public void getEnabled(
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId,
            @WebParam(mode = WebParam.Mode.OUT, name = "enabled", targetNamespace = "")
            javax.xml.ws.Holder<Integer> enabled
    );

    /**
     * 
     * 				
     * 			
     */
    @WebMethod(operationName = "GetMaxSensitivity", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetMaxSensitivity")
    @RequestWrapper(localName = "GetMaxSensitivity", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMaxSensitivity")
    @ResponseWrapper(localName = "GetMaxSensitivityResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMaxSensitivityResponse")
    public void getMaxSensitivity(
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId,
            @WebParam(mode = WebParam.Mode.OUT, name = "maxSensitivity", targetNamespace = "")
            javax.xml.ws.Holder<Integer> maxSensitivity
    );

    /**
     * Returns the regions of the motion detection grid in which motion is being detected and reported. In current Pelco IP-based devices, this action returns the bitmask for the entire available grid. However in Pelco legacy products this action will only return the bitmask of the given region that was passed into the SetMDRegion call.
     * 			
     */
    @WebMethod(operationName = "GetMDRegions", action = "urn:schemas-pelco-com:service:MotionDetection:1#GetMDRegions")
    @RequestWrapper(localName = "GetMDRegions", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMDRegions")
    @ResponseWrapper(localName = "GetMDRegionsResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.GetMDRegionsResponse")
    public void getMDRegions(
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId,
            @WebParam(mode = WebParam.Mode.OUT, name = "regionList", targetNamespace = "")
            javax.xml.ws.Holder<MDRegionList> regionList
    );

    /**
     * Updates the regions of the motion detection grid in which motion should be detected and reported. Creating a region outside the grid will yield a SOAP fault.
     * 			
     */
    @WebMethod(operationName = "SetMDRegions", action = "urn:schemas-pelco-com:service:MotionDetection:1#SetMDRegions")
    @RequestWrapper(localName = "SetMDRegions", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.SetMDRegions")
    @ResponseWrapper(localName = "SetMDRegionsResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.SetMDRegionsResponse")
    public void setMDRegions(
            @WebParam(name = "regionList", targetNamespace = "")
            MDRegionList regionList,
            @WebParam(mode = WebParam.Mode.INOUT, name = "asyncId", targetNamespace = "")
            javax.xml.ws.Holder<Integer> asyncId
    );

    /**
     * Updates the current motion detection configuration.
     */
    @WebMethod(operationName = "SetMDConfiguration", action = "urn:schemas-pelco-com:service:MotionDetection:1#SetMDConfiguration")
    @RequestWrapper(localName = "SetMDConfiguration", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.SetMDConfiguration")
    @ResponseWrapper(localName = "SetMDConfigurationResponse", targetNamespace = "urn:schemas-pelco-com:service:MotionDetection:1", className = "com.cmos.ipa.service.video_surveillance.motionDetectionV1.SetMDConfigurationResponse")
    public void setMDConfiguration(
            @WebParam(name = "mdConfig", targetNamespace = "")
            MDConfig mdConfig
    );
}
