package com.cmos.ipa.service.video_surveillance.metaDataV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:20.704+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:MetaData:1", name = "MetaDataPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MetaDataPortType {

    /**
     * Clears the text to be overlayed on a video frame.
     * 			
     */
    @WebMethod(operationName = "ClearText", action = "urn:schemas-pelco-com:service:MetaData:1#ClearText")
    @RequestWrapper(localName = "ClearText", targetNamespace = "urn:schemas-pelco-com:service:MetaData:1", className = "com.cmos.ipa.service.video_surveillance.metaDataV1.ClearText")
    @ResponseWrapper(localName = "ClearTextResponse", targetNamespace = "urn:schemas-pelco-com:service:MetaData:1", className = "com.cmos.ipa.service.video_surveillance.metaDataV1.ClearTextResponse")
    public void clearText();

    /**
     * Sets the text to be overlayed on a video frame.
     * 			
     */
    @WebMethod(operationName = "SetText", action = "urn:schemas-pelco-com:service:MetaData:1#SetText")
    @RequestWrapper(localName = "SetText", targetNamespace = "urn:schemas-pelco-com:service:MetaData:1", className = "com.cmos.ipa.service.video_surveillance.metaDataV1.SetText")
    @ResponseWrapper(localName = "SetTextResponse", targetNamespace = "urn:schemas-pelco-com:service:MetaData:1", className = "com.cmos.ipa.service.video_surveillance.metaDataV1.SetTextResponse")
    public void setText(
            @WebParam(name = "X", targetNamespace = "")
            short x,
            @WebParam(name = "Y", targetNamespace = "")
            short y,
            @WebParam(name = "TIME", targetNamespace = "")
            long time,
            @WebParam(name = "TEXT", targetNamespace = "")
            String text
    );
}
