
package com.cmos.ipa.service.video_surveillance.metaDataV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:20.622+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class MetaDataPortType_MetaData_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:MetaData:1", "MetaData");

    private MetaDataPortType_MetaData_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MetaData.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MetaData ss = new MetaData(wsdlURL, SERVICE_NAME);
        MetaDataPortType port = ss.getMetaData();  
        
        {
        System.out.println("Invoking clearText...");
        port.clearText();


        }
        {
        System.out.println("Invoking setText...");
        short _setText_x = Short.parseShort("0");
        short _setText_y = Short.parseShort("0");
        long _setText_time = 0;
        String _setText_text = "";
        port.setText(_setText_x, _setText_y, _setText_time, _setText_text);


        }

        System.exit(0);
    }

}
