package com.cmos.ipa.service.video_surveillance.imagingConfigurationV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * 
 * 		
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:15.500+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ImagingConfiguration", 
                  wsdlLocation = "file:wsdl/ImagingConfigurationV1.wsdl",
                  targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1") 
public class ImagingConfiguration extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.pelco.com/api/ImagingConfiguration/1", "ImagingConfiguration");
    public final static QName ImagingConfiguration = new QName("http://www.pelco.com/api/ImagingConfiguration/1", "ImagingConfiguration");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/ImagingConfigurationV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImagingConfiguration.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/ImagingConfigurationV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImagingConfiguration(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImagingConfiguration(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImagingConfiguration() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ImagingConfiguration(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ImagingConfiguration(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ImagingConfiguration(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ImagingConfigurationPortType
     */
    @WebEndpoint(name = "ImagingConfiguration")
    public ImagingConfigurationPortType getImagingConfiguration() {
        return super.getPort(ImagingConfiguration, ImagingConfigurationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImagingConfigurationPortType
     */
    @WebEndpoint(name = "ImagingConfiguration")
    public ImagingConfigurationPortType getImagingConfiguration(WebServiceFeature... features) {
        return super.getPort(ImagingConfiguration, ImagingConfigurationPortType.class, features);
    }

}
