package com.cmos.ipa.service.video_surveillance.imagingConfigurationV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:15.487+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", name = "ImagingConfigurationPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ImagingConfigurationPortType {

    /**
     * Returns the current ColorPalette setting.
     */
    @WebMethod(operationName = "GetColorPalette", action = "http://www.pelco.com/api/ImagingConfiguration/1/GetColorPalette")
    @RequestWrapper(localName = "GetColorPalette", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetColorPalette")
    @ResponseWrapper(localName = "GetColorPaletteResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetColorPaletteResponse")
    @WebResult(name = "ColorPalette", targetNamespace = "")
    public ColorPalette getColorPalette();

    /**
     * Gets the Image Enhancement tuning value on the camera.
     */
    @WebMethod(operationName = "GetImageEnhancementLevel", action = "http://www.pelco.com/api/ImagingConfiguration/1/GetImageEnhancementLevel")
    @RequestWrapper(localName = "GetImageEnhancementLevel", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetImageEnhancementLevel")
    @ResponseWrapper(localName = "GetImageEnhancementLevelResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetImageEnhancementLevelResponse")
    @WebResult(name = "ImageEnhancementLevel", targetNamespace = "")
    public int getImageEnhancementLevel();

    /**
     * Sets the current ColorPalette setting.
     */
    @WebMethod(operationName = "SetColorPalette", action = "http://www.pelco.com/api/ImagingConfiguration/1/SetColorPalette")
    @RequestWrapper(localName = "SetColorPalette", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetColorPalette")
    @ResponseWrapper(localName = "SetColorPaletteResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetColorPaletteResponse")
    public void setColorPalette(
            @WebParam(name = "ColorPalette", targetNamespace = "")
            ColorPalette colorPalette
    );

    /**
     * Triggers immediate recalibration of the camera.
     */
    @WebMethod(operationName = "CalibrateNow", action = "http://www.pelco.com/api/ImagingConfiguration/1/CalibrateNow")
    @RequestWrapper(localName = "CalibrateNow", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.CalibrateNow")
    @ResponseWrapper(localName = "CalibrateNowResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.CalibrateNowResponse")
    public void calibrateNow();

    /**
     * Returns the available ColorPalette settings.
     */
    @WebMethod(operationName = "GetAllColorPalettes", action = "http://www.pelco.com/api/ImagingConfiguration/1/GetAllColorPalettes")
    @RequestWrapper(localName = "GetAllColorPalettes", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetAllColorPalettes")
    @ResponseWrapper(localName = "GetAllColorPalettesResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetAllColorPalettesResponse")
    @WebResult(name = "ColorPalette", targetNamespace = "")
    public java.util.List<ColorPalette> getAllColorPalettes();

    /**
     * Returns the current RecalibrationMode setting.
     */
    @WebMethod(operationName = "GetRecalibrationMode", action = "http://www.pelco.com/api/ImagingConfiguration/1/GetRecalibrationMode")
    @RequestWrapper(localName = "GetRecalibrationMode", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetRecalibrationMode")
    @ResponseWrapper(localName = "GetRecalibrationModeResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetRecalibrationModeResponse")
    @WebResult(name = "RecalibrationMode", targetNamespace = "")
    public RecalibrationMode getRecalibrationMode();

    /**
     * Sets the current RecalibrationMode setting.
     */
    @WebMethod(operationName = "SetRecalibrationMode", action = "http://www.pelco.com/api/ImagingConfiguration/1/SetRecalibrationMode")
    @RequestWrapper(localName = "SetRecalibrationMode", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetRecalibrationMode")
    @ResponseWrapper(localName = "SetRecalibrationModeResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetRecalibrationModeResponse")
    public void setRecalibrationMode(
            @WebParam(name = "RecalibrationMode", targetNamespace = "")
            RecalibrationMode recalibrationMode
    );

    /**
     * Gets the delay time (in minutes) between camera recalibrations.
     */
    @WebMethod(operationName = "GetCalibrationInterval", action = "http://www.pelco.com/api/ImagingConfiguration/1/GetCalibrationInterval")
    @RequestWrapper(localName = "GetCalibrationInterval", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetCalibrationInterval")
    @ResponseWrapper(localName = "GetCalibrationIntervalResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetCalibrationIntervalResponse")
    @WebResult(name = "CalibrationInterval", targetNamespace = "")
    public javax.xml.datatype.Duration getCalibrationInterval();

    /**
     * Sets the Image Enhancement tuning value on the camera.
     */
    @WebMethod(operationName = "SetImageEnhancementLevel", action = "http://www.pelco.com/api/ImagingConfiguration/1/SetImageEnhancementLevel")
    @RequestWrapper(localName = "SetImageEnhancementLevel", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetImageEnhancementLevel")
    @ResponseWrapper(localName = "SetImageEnhancementLevelResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetImageEnhancementLevelResponse")
    public void setImageEnhancementLevel(
            @WebParam(name = "ImageEnhancementLevel", targetNamespace = "")
            int imageEnhancementLevel
    );

    /**
     * Returns the current Sharpness setting.
     */
    @WebMethod(operationName = "GetSharpness", action = "http://www.pelco.com/api/ImagingConfiguration/1/GetSharpness")
    @RequestWrapper(localName = "GetSharpness", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetSharpness")
    @ResponseWrapper(localName = "GetSharpnessResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.GetSharpnessResponse")
    @WebResult(name = "Sharpness", targetNamespace = "")
    public ModeValuePair getSharpness();

    /**
     * Sets the current Sharpness setting.
     */
    @WebMethod(operationName = "SetSharpness", action = "http://www.pelco.com/api/ImagingConfiguration/1/SetSharpness")
    @RequestWrapper(localName = "SetSharpness", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetSharpness")
    @ResponseWrapper(localName = "SetSharpnessResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetSharpnessResponse")
    public void setSharpness(
            @WebParam(name = "Sharpness", targetNamespace = "")
            ModeValuePair sharpness
    );

    /**
     * Immediate delay of recalibration of the camera for a specified duration.
     */
    @WebMethod(operationName = "DelayRecalibration", action = "http://www.pelco.com/api/ImagingConfiguration/1/DelayRecalibration")
    @RequestWrapper(localName = "DelayRecalibration", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.DelayRecalibration")
    @ResponseWrapper(localName = "DelayRecalibrationResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.DelayRecalibrationResponse")
    public void delayRecalibration(
            @WebParam(name = "CalibrationDelay", targetNamespace = "")
            javax.xml.datatype.Duration calibrationDelay
    );

    /**
     * Sets the delay time (in minutes) between camera recalibrations.
     */
    @WebMethod(operationName = "SetCalibrationInterval", action = "http://www.pelco.com/api/ImagingConfiguration/1/SetCalibrationInterval")
    @RequestWrapper(localName = "SetCalibrationInterval", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetCalibrationInterval")
    @ResponseWrapper(localName = "SetCalibrationIntervalResponse", targetNamespace = "http://www.pelco.com/api/ImagingConfiguration/1", className = "com.cmos.ipa.service.video_surveillance.imagingConfigurationV1.SetCalibrationIntervalResponse")
    public void setCalibrationInterval(
            @WebParam(name = "CalibrationInterval", targetNamespace = "")
            javax.xml.datatype.Duration calibrationInterval
    );
}
