package com.cmos.ipa.service.video_surveillance.streamDiscoveryV1;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:48.789+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:StreamDiscovery:1", name = "StreamDiscoveryPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface StreamDiscoveryPortType {

    /**
     * Queries a device for its available streams.
     */
    @WebMethod(operationName = "StreamQuery", action = "urn:schemas-pelco-com:service:StreamDiscovery:1#StreamQuery")
    @RequestWrapper(localName = "StreamQuery", targetNamespace = "urn:schemas-pelco-com:service:StreamDiscovery:1", className = "com.cmos.ipa.service.video_surveillance.streamDiscoveryV1.StreamQuery")
    @ResponseWrapper(localName = "StreamQueryResponse", targetNamespace = "urn:schemas-pelco-com:service:StreamDiscovery:1", className = "com.cmos.ipa.service.video_surveillance.streamDiscoveryV1.StreamQueryResponse")
    @WebResult(name = "connectionList", targetNamespace = "")
    public ConnectionList streamQuery();
}
