package com.cmos.ipa.service.video_surveillance.deviceRegistryV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:12.694+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", name = "DeviceRegistryPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DeviceRegistryPortType {

    /**
     * Returns configuration data on all devices with stored information.  The GetDevices action can be a process intensive task. It is highly recommended that you properly filter out off line devices in the search results, with the UpnpDvcQuery instance. Ideally you should also only search for recently updated or added devices to further help performance.
     *       
     */
    @WebMethod(operationName = "GetDevices", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetDevices")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetDevicesResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", partName = "parameters")
    public GetDevicesResponse getDevices(
            @WebParam(partName = "header", name = "evHeader", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", header = true)
            HeaderType header,
            @WebParam(partName = "parameters", name = "GetDevices", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1")
            GetDevices parameters
    );

    /**
     * Returns a system attribute value
     *       
     */
    @WebMethod(operationName = "SysCfgGet", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#SysCfgGet")
    @RequestWrapper(localName = "SysCfgGet", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.SysCfgGet")
    @ResponseWrapper(localName = "SysCfgGetResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.SysCfgGetResponse")
    public void sysCfgGet(
            @WebParam(name = "name", targetNamespace = "")
            String name,
            @WebParam(mode = WebParam.Mode.OUT, name = "value", targetNamespace = "")
            javax.xml.ws.Holder<String> value,
            @WebParam(mode = WebParam.Mode.OUT, name = "found", targetNamespace = "")
            javax.xml.ws.Holder<String> found
    );

    /**
     * Returns a specific attribute value for a specified device
     *       
     */
    @WebMethod(operationName = "GetDeviceAttributeValue", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetDeviceAttributeValue")
    @RequestWrapper(localName = "GetDeviceAttributeValue", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceAttributeValue")
    @ResponseWrapper(localName = "GetDeviceAttributeValueResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceAttributeValueResponse")
    public void getDeviceAttributeValue(
            @WebParam(name = "deviceUdn", targetNamespace = "")
            String deviceUdn,
            @WebParam(name = "attributeName", targetNamespace = "")
            String attributeName,
            @WebParam(mode = WebParam.Mode.OUT, name = "found", targetNamespace = "")
            javax.xml.ws.Holder<String> found,
            @WebParam(mode = WebParam.Mode.OUT, name = "attributeValue", targetNamespace = "")
            javax.xml.ws.Holder<String> attributeValue
    );

    /**
     * Returns devices that have the specified attribute value
     *       
     */
    @WebMethod(operationName = "GetDevicesByAttrValue", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetDevicesByAttrValue")
    @RequestWrapper(localName = "GetDevicesByAttrValue", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDevicesByAttrValue")
    @ResponseWrapper(localName = "GetDevicesByAttrValueResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDevicesByAttrValueResponse")
    @WebResult(name = "page", targetNamespace = "")
    public String getDevicesByAttrValue(
            @WebParam(name = "attributeName", targetNamespace = "")
            String attributeName,
            @WebParam(name = "attributeValue", targetNamespace = "")
            String attributeValue,
            @WebParam(name = "pageReq", targetNamespace = "")
            String pageReq
    );

    /**
     * Returns a specific attribute value for a specified device and service
     *       
     */
    @WebMethod(operationName = "GetDeviceServiceAttributeValue", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetDeviceServiceAttributeValue")
    @RequestWrapper(localName = "GetDeviceServiceAttributeValue", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceServiceAttributeValue")
    @ResponseWrapper(localName = "GetDeviceServiceAttributeValueResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceServiceAttributeValueResponse")
    public void getDeviceServiceAttributeValue(
            @WebParam(name = "deviceUdn", targetNamespace = "")
            String deviceUdn,
            @WebParam(name = "serviceId", targetNamespace = "")
            String serviceId,
            @WebParam(name = "attributeName", targetNamespace = "")
            String attributeName,
            @WebParam(mode = WebParam.Mode.OUT, name = "found", targetNamespace = "")
            javax.xml.ws.Holder<String> found,
            @WebParam(mode = WebParam.Mode.OUT, name = "attributeValue", targetNamespace = "")
            javax.xml.ws.Holder<String> attributeValue
    );

    /**
     * Returns specific information for a specified device's service
     *       
     */
    @WebMethod(operationName = "GetDeviceServiceInfo", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetDeviceServiceInfo")
    @RequestWrapper(localName = "GetDeviceServiceInfo", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceServiceInfo")
    @ResponseWrapper(localName = "GetDeviceServiceInfoResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceServiceInfoResponse")
    @WebResult(name = "page", targetNamespace = "")
    public ServiceInfoPage getDeviceServiceInfo(
            @WebParam(name = "deviceUdn", targetNamespace = "")
            String deviceUdn,
            @WebParam(name = "svcInfoFlags", targetNamespace = "")
            String svcInfoFlags,
            @WebParam(name = "pageReq", targetNamespace = "")
            String pageReq
    );

    /**
     * Returns a set of device results
     *       
     */
    @WebMethod(operationName = "GetPage", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetPage")
    @RequestWrapper(localName = "GetPage", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetPage")
    @ResponseWrapper(localName = "GetPageResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetPageResponse")
    @WebResult(name = "page", targetNamespace = "")
    public Page getPage(
            @WebParam(name = "pageReq", targetNamespace = "")
            PageReq pageReq
    );

    /**
     * Returns all attributes for a specified device
     *       
     */
    @WebMethod(operationName = "GetDeviceAttributes", action = "urn:schemas-pelco-com:service:DeviceRegistry:1#GetDeviceAttributes")
    @RequestWrapper(localName = "GetDeviceAttributes", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceAttributes")
    @ResponseWrapper(localName = "GetDeviceAttributesResponse", targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1", className = "com.cmos.ipa.service.video_surveillance.deviceRegistryV1.GetDeviceAttributesResponse")
    @WebResult(name = "page", targetNamespace = "")
    public String getDeviceAttributes(
            @WebParam(name = "deviceUdn", targetNamespace = "")
            String deviceUdn,
            @WebParam(name = "pageReq", targetNamespace = "")
            String pageReq
    );
}
