
package com.cmos.ipa.service.video_surveillance.deviceRegistryV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:12.583+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class DeviceRegistryPortType_DeviceRegistry_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:DeviceRegistry:1", "DeviceRegistry");

    private DeviceRegistryPortType_DeviceRegistry_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DeviceRegistry.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DeviceRegistry ss = new DeviceRegistry(wsdlURL, SERVICE_NAME);
        DeviceRegistryPortType port = ss.getDeviceRegistry();  
        
        {
        System.out.println("Invoking getDevices...");
        HeaderType _getDevices_header = null;
        GetDevices _getDevices_parameters = null;
        GetDevicesResponse _getDevices__return = port.getDevices(_getDevices_header, _getDevices_parameters);
        System.out.println("getDevices.result=" + _getDevices__return);


        }
        {
        System.out.println("Invoking sysCfgGet...");
        String _sysCfgGet_name = "";
        javax.xml.ws.Holder<String> _sysCfgGet_value = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _sysCfgGet_found = new javax.xml.ws.Holder<String>();
        port.sysCfgGet(_sysCfgGet_name, _sysCfgGet_value, _sysCfgGet_found);

        System.out.println("sysCfgGet._sysCfgGet_value=" + _sysCfgGet_value.value);
        System.out.println("sysCfgGet._sysCfgGet_found=" + _sysCfgGet_found.value);

        }
        {
        System.out.println("Invoking getDeviceAttributeValue...");
        String _getDeviceAttributeValue_deviceUdn = "";
        String _getDeviceAttributeValue_attributeName = "";
        javax.xml.ws.Holder<String> _getDeviceAttributeValue_found = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getDeviceAttributeValue_attributeValue = new javax.xml.ws.Holder<String>();
        port.getDeviceAttributeValue(_getDeviceAttributeValue_deviceUdn, _getDeviceAttributeValue_attributeName, _getDeviceAttributeValue_found, _getDeviceAttributeValue_attributeValue);

        System.out.println("getDeviceAttributeValue._getDeviceAttributeValue_found=" + _getDeviceAttributeValue_found.value);
        System.out.println("getDeviceAttributeValue._getDeviceAttributeValue_attributeValue=" + _getDeviceAttributeValue_attributeValue.value);

        }
        {
        System.out.println("Invoking getDevicesByAttrValue...");
        String _getDevicesByAttrValue_attributeName = "";
        String _getDevicesByAttrValue_attributeValue = "";
        String _getDevicesByAttrValue_pageReq = "";
        String _getDevicesByAttrValue__return = port.getDevicesByAttrValue(_getDevicesByAttrValue_attributeName, _getDevicesByAttrValue_attributeValue, _getDevicesByAttrValue_pageReq);
        System.out.println("getDevicesByAttrValue.result=" + _getDevicesByAttrValue__return);


        }
        {
        System.out.println("Invoking getDeviceServiceAttributeValue...");
        String _getDeviceServiceAttributeValue_deviceUdn = "";
        String _getDeviceServiceAttributeValue_serviceId = "";
        String _getDeviceServiceAttributeValue_attributeName = "";
        javax.xml.ws.Holder<String> _getDeviceServiceAttributeValue_found = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _getDeviceServiceAttributeValue_attributeValue = new javax.xml.ws.Holder<String>();
        port.getDeviceServiceAttributeValue(_getDeviceServiceAttributeValue_deviceUdn, _getDeviceServiceAttributeValue_serviceId, _getDeviceServiceAttributeValue_attributeName, _getDeviceServiceAttributeValue_found, _getDeviceServiceAttributeValue_attributeValue);

        System.out.println("getDeviceServiceAttributeValue._getDeviceServiceAttributeValue_found=" + _getDeviceServiceAttributeValue_found.value);
        System.out.println("getDeviceServiceAttributeValue._getDeviceServiceAttributeValue_attributeValue=" + _getDeviceServiceAttributeValue_attributeValue.value);

        }
        {
        System.out.println("Invoking getDeviceServiceInfo...");
        String _getDeviceServiceInfo_deviceUdn = "";
        String _getDeviceServiceInfo_svcInfoFlags = "";
        String _getDeviceServiceInfo_pageReq = "";
        ServiceInfoPage _getDeviceServiceInfo__return = port.getDeviceServiceInfo(_getDeviceServiceInfo_deviceUdn, _getDeviceServiceInfo_svcInfoFlags, _getDeviceServiceInfo_pageReq);
        System.out.println("getDeviceServiceInfo.result=" + _getDeviceServiceInfo__return);


        }
        {
        System.out.println("Invoking getPage...");
        PageReq _getPage_pageReq = null;
        Page _getPage__return = port.getPage(_getPage_pageReq);
        System.out.println("getPage.result=" + _getPage__return);


        }
        {
        System.out.println("Invoking getDeviceAttributes...");
        String _getDeviceAttributes_deviceUdn = "";
        String _getDeviceAttributes_pageReq = "";
        String _getDeviceAttributes__return = port.getDeviceAttributes(_getDeviceAttributes_deviceUdn, _getDeviceAttributes_pageReq);
        System.out.println("getDeviceAttributes.result=" + _getDeviceAttributes__return);


        }

        System.exit(0);
    }

}
