package com.cmos.ipa.service.video_surveillance.deviceRegistryV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:12.705+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "DeviceRegistry", 
                  wsdlLocation = "file:wsdl/DeviceRegistryV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:DeviceRegistry:1") 
public class DeviceRegistry extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:DeviceRegistry:1", "DeviceRegistry");
    public final static QName DeviceRegistry = new QName("urn:schemas-pelco-com:service:DeviceRegistry:1", "DeviceRegistry");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/DeviceRegistryV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeviceRegistry.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/DeviceRegistryV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeviceRegistry(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeviceRegistry(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceRegistry() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DeviceRegistry(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeviceRegistry(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeviceRegistry(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DeviceRegistryPortType
     */
    @WebEndpoint(name = "DeviceRegistry")
    public DeviceRegistryPortType getDeviceRegistry() {
        return super.getPort(DeviceRegistry, DeviceRegistryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceRegistryPortType
     */
    @WebEndpoint(name = "DeviceRegistry")
    public DeviceRegistryPortType getDeviceRegistry(WebServiceFeature... features) {
        return super.getPort(DeviceRegistry, DeviceRegistryPortType.class, features);
    }

}
