
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.scriptControlV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:37.900+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "ScriptControl",
                      portName = "ScriptControl",
                      targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1",
                      wsdlLocation = "file:a/ScriptControlV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType")
                      
public class ScriptControlImpl implements ScriptControlPortType {

    private static final Logger LOG = Logger.getLogger(ScriptControlImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#executeScript(java.lang.String  scriptName )*
     */
    public int executeScript(String scriptName) {
        LOG.info("Executing operation executeScript");
        System.out.println(scriptName);
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#haltScript(java.lang.String  scriptName ,)java.lang.Integer  pid )*
     */
    public void haltScript(String scriptName,Integer pid) {
        LOG.info("Executing operation haltScript");
        System.out.println(scriptName);
        System.out.println(pid);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#beginScript(java.lang.String  scriptName )*
     */
    public void beginScript(String scriptName) {
        LOG.info("Executing operation beginScript");
        System.out.println(scriptName);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#endScript(java.lang.String  scriptName )*
     */
    public void endScript(String scriptName) {
        LOG.info("Executing operation endScript");
        System.out.println(scriptName);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#cancelScript(java.lang.String  scriptName )*
     */
    public void cancelScript(String scriptName) {
        LOG.info("Executing operation cancelScript");
        System.out.println(scriptName);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#deleteScript(java.lang.String  scriptName )*
     */
    public void deleteScript(String scriptName) {
        LOG.info("Executing operation deleteScript");
        System.out.println(scriptName);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptControlPortType#queryScripts(com.cmos.ipa.service.video_surveillance.scriptControlV1.ScriptQuery  scriptQuery )*
     */
    public ScriptList queryScripts(ScriptQuery scriptQuery) {
        LOG.info("Executing operation queryScripts");
        System.out.println(scriptQuery);
        try {
            ScriptList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
