
package com.cmos.ipa.service.video_surveillance.scriptControlV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:37.832+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class ScriptControlPortType_ScriptControl_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:ScriptControl:1", "ScriptControl");

    private ScriptControlPortType_ScriptControl_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ScriptControl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ScriptControl ss = new ScriptControl(wsdlURL, SERVICE_NAME);
        ScriptControlPortType port = ss.getScriptControl();  
        
        {
        System.out.println("Invoking executeScript...");
        String _executeScript_scriptName = "";
        int _executeScript__return = port.executeScript(_executeScript_scriptName);
        System.out.println("executeScript.result=" + _executeScript__return);


        }
        {
        System.out.println("Invoking haltScript...");
        String _haltScript_scriptName = "";
        Integer _haltScript_pid = null;
        port.haltScript(_haltScript_scriptName, _haltScript_pid);


        }
        {
        System.out.println("Invoking beginScript...");
        String _beginScript_scriptName = "";
        port.beginScript(_beginScript_scriptName);


        }
        {
        System.out.println("Invoking endScript...");
        String _endScript_scriptName = "";
        port.endScript(_endScript_scriptName);


        }
        {
        System.out.println("Invoking cancelScript...");
        String _cancelScript_scriptName = "";
        port.cancelScript(_cancelScript_scriptName);


        }
        {
        System.out.println("Invoking deleteScript...");
        String _deleteScript_scriptName = "";
        port.deleteScript(_deleteScript_scriptName);


        }
        {
        System.out.println("Invoking queryScripts...");
        ScriptQuery _queryScripts_scriptQuery = null;
        ScriptList _queryScripts__return = port.queryScripts(_queryScripts_scriptQuery);
        System.out.println("queryScripts.result=" + _queryScripts__return);


        }

        System.exit(0);
    }

}
