package com.cmos.ipa.service.video_surveillance.scriptControlV1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:37.922+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", name = "ScriptControlPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ScriptControlPortType {

    /**
     * Causes the locally stored script indicated by scriptName to be executed.
     * 			
     */
    @WebMethod(operationName = "ExecuteScript", action = "urn:schemas-pelco-com:service:ScriptControl:1#ExecuteScript")
    @RequestWrapper(localName = "ExecuteScript", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.ExecuteScript")
    @ResponseWrapper(localName = "ExecuteScriptResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.ExecuteScriptResponse")
    @WebResult(name = "pid", targetNamespace = "")
    public int executeScript(
            @WebParam(name = "scriptName", targetNamespace = "")
            String scriptName
    );

    /**
     * Causes an instance of a script indicated by pid to 
     * 				be stopped, if currently running. 
     * 			
     */
    @WebMethod(operationName = "HaltScript", action = "urn:schemas-pelco-com:service:ScriptControl:1#HaltScript")
    @RequestWrapper(localName = "HaltScript", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.HaltScript")
    @ResponseWrapper(localName = "HaltScriptResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.HaltScriptResponse")
    public void haltScript(
            @WebParam(name = "scriptName", targetNamespace = "")
            String scriptName,
            @WebParam(name = "pid", targetNamespace = "")
            Integer pid
    );

    /**
     * Causes the service instance to begin "recording" or "programming"
     * the script. The name of the script is set in scriptName.
     * 
     * 
     *       
     */
    @WebMethod(operationName = "BeginScript", action = "urn:schemas-pelco-com:service:ScriptControl:1#BeginScript")
    @RequestWrapper(localName = "BeginScript", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.BeginScript")
    @ResponseWrapper(localName = "BeginScriptResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.BeginScriptResponse")
    public void beginScript(
            @WebParam(name = "scriptName", targetNamespace = "")
            String scriptName
    );

    /**
     * Causes the service instance to end the "recording" or
     * "programming" of a specific script and save it using a given scriptName.
     *       
     */
    @WebMethod(operationName = "EndScript", action = "urn:schemas-pelco-com:service:ScriptControl:1#EndScript")
    @RequestWrapper(localName = "EndScript", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.EndScript")
    @ResponseWrapper(localName = "EndScriptResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.EndScriptResponse")
    public void endScript(
            @WebParam(name = "scriptName", targetNamespace = "")
            String scriptName
    );

    /**
     * Causes the service instance to cancel the "recording" or
     * "programming" of the script indicated by scriptName. Nothing is saved.
     *       
     */
    @WebMethod(operationName = "CancelScript", action = "urn:schemas-pelco-com:service:ScriptControl:1#CancelScript")
    @RequestWrapper(localName = "CancelScript", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.CancelScript")
    @ResponseWrapper(localName = "CancelScriptResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.CancelScriptResponse")
    public void cancelScript(
            @WebParam(name = "scriptName", targetNamespace = "")
            String scriptName
    );

    /**
     * Causes the service instance to delete from its list of scripts the script indicated by scriptName.
     *       
     */
    @WebMethod(operationName = "DeleteScript", action = "urn:schemas-pelco-com:service:ScriptControl:1#DeleteScript")
    @RequestWrapper(localName = "DeleteScript", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.DeleteScript")
    @ResponseWrapper(localName = "DeleteScriptResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.DeleteScriptResponse")
    public void deleteScript(
            @WebParam(name = "scriptName", targetNamespace = "")
            String scriptName
    );

    /**
     * Retrieves a list of names of locally stored scripts from the service instance.
     *       
     */
    @WebMethod(operationName = "QueryScripts", action = "urn:schemas-pelco-com:service:ScriptControl:1#QueryScripts")
    @RequestWrapper(localName = "QueryScripts", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.QueryScripts")
    @ResponseWrapper(localName = "QueryScriptsResponse", targetNamespace = "urn:schemas-pelco-com:service:ScriptControl:1", className = "com.cmos.ipa.service.video_surveillance.scriptControlV1.QueryScriptsResponse")
    @WebResult(name = "scriptList", targetNamespace = "")
    public ScriptList queryScripts(
            @WebParam(name = "scriptQuery", targetNamespace = "")
            ScriptQuery scriptQuery
    );
}
