package com.cmos.ipa.service.video_surveillance.streamControlV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:46.203+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "StreamControl", 
                  wsdlLocation = "file:wsdl/StreamControlV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:StreamControl:1") 
public class StreamControl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:StreamControl:1", "StreamControl");
    public final static QName StreamControl = new QName("urn:schemas-pelco-com:service:StreamControl:1", "StreamControl");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/StreamControlV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StreamControl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/StreamControlV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StreamControl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StreamControl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StreamControl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StreamControl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StreamControl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StreamControl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StreamControlPortType
     */
    @WebEndpoint(name = "StreamControl")
    public StreamControlPortType getStreamControl() {
        return super.getPort(StreamControl, StreamControlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StreamControlPortType
     */
    @WebEndpoint(name = "StreamControl")
    public StreamControlPortType getStreamControl(WebServiceFeature... features) {
        return super.getPort(StreamControl, StreamControlPortType.class, features);
    }

}
