package com.cmos.ipa.service.video_surveillance.videoOutputV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This services allows clients to query existing streams and active sessions along with their parameters. 
 * Other uses for this service include initiating a stream, terminating an existing stream and refreshing sessions.
 *     
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:19:02.855+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "VideoOutput", 
                  wsdlLocation = "file:wsdl/VideoOutputV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:VideoOutput:1") 
public class VideoOutput extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:VideoOutput:1", "VideoOutput");
    public final static QName VideoOutput = new QName("urn:schemas-pelco-com:service:VideoOutput:1", "VideoOutput");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/VideoOutputV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VideoOutput.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/VideoOutputV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VideoOutput(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VideoOutput(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VideoOutput() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VideoOutput(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VideoOutput(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VideoOutput(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VideoOutputPortType
     */
    @WebEndpoint(name = "VideoOutput")
    public VideoOutputPortType getVideoOutput() {
        return super.getPort(VideoOutput, VideoOutputPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VideoOutputPortType
     */
    @WebEndpoint(name = "VideoOutput")
    public VideoOutputPortType getVideoOutput(WebServiceFeature... features) {
        return super.getPort(VideoOutput, VideoOutputPortType.class, features);
    }

}
