
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cmos.ipa.service.video_surveillance.videoOutputV1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:19:02.784+08:00
 * Generated source version: 3.1.6
 * 
 */

@WebService(
                      serviceName = "VideoOutput",
                      portName = "VideoOutput",
                      targetNamespace = "urn:schemas-pelco-com:service:VideoOutput:1",
                      wsdlLocation = "file:a/VideoOutputV1.wsdl",
                      endpointInterface = "com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType")
                      
public class VideoOutputImpl implements VideoOutputPortType {

    private static final Logger LOG = Logger.getLogger(VideoOutputImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#getSessionParameters(java.lang.String  sessionId )*
     */
    public com.cmos.ipa.service.video_surveillance.videoOutputV1.StreamParameters getSessionParameters(String sessionId) {
        LOG.info("Executing operation getSessionParameters");
        System.out.println(sessionId);
        try {
            com.cmos.ipa.service.video_surveillance.videoOutputV1.StreamParameters _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#disconnect(java.lang.String  sessionId ,)java.lang.Integer  asyncId )*
     */
    public void disconnect(String sessionId,javax.xml.ws.Holder<Integer> asyncId) {
        LOG.info("Executing operation disconnect");
        System.out.println(sessionId);
        System.out.println(asyncId.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#query(com.cmos.ipa.service.video_surveillance.videoOutputV1.StreamQuery  streamQuery ,)java.lang.Integer  asyncId ,)com.cmos.ipa.service.video_surveillance.videoOutputV1.StreamCatalog  streamCatalog )*
     */
    public void query(StreamQuery streamQuery,javax.xml.ws.Holder<Integer> asyncId,javax.xml.ws.Holder<StreamCatalog> streamCatalog) {
        LOG.info("Executing operation query");
        System.out.println(streamQuery);
        System.out.println(asyncId.value);
        try {
            StreamCatalog streamCatalogValue = null;
            streamCatalog.value = streamCatalogValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#connect(com.cmos.ipa.service.video_surveillance.videoOutputV1.StreamParameters  streamParameters ,)java.lang.Integer  asyncId )*
     */
    public void connect(javax.xml.ws.Holder<StreamParameters> streamParameters,javax.xml.ws.Holder<Integer> asyncId) {
        LOG.info("Executing operation connect");
        System.out.println(streamParameters.value);
        System.out.println(asyncId.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#getActiveSessions(java.lang.Integer  activeSessions ,)java.lang.Integer  maxSessions )*
     */
    public void getActiveSessions(javax.xml.ws.Holder<Integer> activeSessions,javax.xml.ws.Holder<Integer> maxSessions) {
        LOG.info("Executing operation getActiveSessions");
        try {
            Integer activeSessionsValue = null;
            activeSessions.value = activeSessionsValue;
            Integer maxSessionsValue = null;
            maxSessions.value = maxSessionsValue;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#getActiveSessionIds(*
     */
    public Sessions getActiveSessionIds() {
        LOG.info("Executing operation getActiveSessionIds");
        try {
            Sessions _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cmos.ipa.service.video_surveillance.videoOutputV1.VideoOutputPortType#refreshSession(java.lang.String  sessionId ,)int  refreshInterval )*
     */
    public void refreshSession(String sessionId,int refreshInterval) {
        LOG.info("Executing operation refreshSession");
        System.out.println(sessionId);
        System.out.println(refreshInterval);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
