
package com.cmos.ipa.service.video_surveillance.positioningControlV1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:32.298+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class PositioningControlPortType_PositioningControl_Client {

    private static final QName SERVICE_NAME = new QName("urn:schemas-pelco-com:service:PositioningControl:1", "PositioningControl");

    private PositioningControlPortType_PositioningControl_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PositioningControl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PositioningControl ss = new PositioningControl(wsdlURL, SERVICE_NAME);
        PositioningControlPortType port = ss.getPositioningControl();  
        
        {
        System.out.println("Invoking getPositionEventInterval...");
        String _getPositionEventInterval__return = port.getPositionEventInterval();
        System.out.println("getPositionEventInterval.result=" + _getPositionEventInterval__return);


        }
        {
        System.out.println("Invoking setPosition...");
        Velocity _setPosition_position = null;
        port.setPosition(_setPosition_position);


        }
        {
        System.out.println("Invoking initializePosition...");
        Velocity _initializePosition_position = null;
        port.initializePosition(_initializePosition_position);


        }
        {
        System.out.println("Invoking setPositionEventInterval...");
        String _setPositionEventInterval_positionEventInterval = "";
        port.setPositionEventInterval(_setPositionEventInterval_positionEventInterval);


        }
        {
        System.out.println("Invoking setVelocity...");
        Velocity _setVelocity_velocity = null;
        port.setVelocity(_setVelocity_velocity);


        }
        {
        System.out.println("Invoking getSpeedProfile...");
        String _getSpeedProfile_profileId = "";
        SpeedProfile _getSpeedProfile__return = port.getSpeedProfile(_getSpeedProfile_profileId);
        System.out.println("getSpeedProfile.result=" + _getSpeedProfile__return);


        }
        {
        System.out.println("Invoking getVelocityURL...");
        String _getVelocityURL__return = port.getVelocityURL();
        System.out.println("getVelocityURL.result=" + _getVelocityURL__return);


        }
        {
        System.out.println("Invoking getPosition...");
        Velocity _getPosition__return = port.getPosition();
        System.out.println("getPosition.result=" + _getPosition__return);


        }
        {
        System.out.println("Invoking getVelocity...");
        Velocity _getVelocity__return = port.getVelocity();
        System.out.println("getVelocity.result=" + _getVelocity__return);


        }
        {
        System.out.println("Invoking getVelocityLimits...");
        VelocityLimits _getVelocityLimits__return = port.getVelocityLimits();
        System.out.println("getVelocityLimits.result=" + _getVelocityLimits__return);


        }
        {
        System.out.println("Invoking getAllSpeedProfiles...");
        java.util.List<SpeedProfile> _getAllSpeedProfiles__return = port.getAllSpeedProfiles();
        System.out.println("getAllSpeedProfiles.result=" + _getAllSpeedProfiles__return);


        }
        {
        System.out.println("Invoking getPositionLimits...");
        AxisLimits _getPositionLimits__return = port.getPositionLimits();
        System.out.println("getPositionLimits.result=" + _getPositionLimits__return);


        }
        {
        System.out.println("Invoking restoreDefaultPositionLimits...");
        port.restoreDefaultPositionLimits();


        }
        {
        System.out.println("Invoking enableSpeedProfile...");
        String _enableSpeedProfile_profileId = "";
        port.enableSpeedProfile(_enableSpeedProfile_profileId);


        }
        {
        System.out.println("Invoking restoreDefaultSpeedProfile...");
        port.restoreDefaultSpeedProfile();


        }
        {
        System.out.println("Invoking getEnabledSpeedProfile...");
        SpeedProfile _getEnabledSpeedProfile__return = port.getEnabledSpeedProfile();
        System.out.println("getEnabledSpeedProfile.result=" + _getEnabledSpeedProfile__return);


        }
        {
        System.out.println("Invoking setAzimuthZero...");
        int _setAzimuthZero_azimuthZero = 0;
        port.setAzimuthZero(_setAzimuthZero_azimuthZero);


        }
        {
        System.out.println("Invoking getAzimuthZero...");
        int _getAzimuthZero__return = port.getAzimuthZero();
        System.out.println("getAzimuthZero.result=" + _getAzimuthZero__return);


        }
        {
        System.out.println("Invoking viewObject...");
        Velocity _viewObject_position = null;
        long _viewObject_radius = 0;
        port.viewObject(_viewObject_position, _viewObject_radius);


        }

        System.exit(0);
    }

}
