package com.cmos.ipa.service.video_surveillance.positioningControlV1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This service allows control over a device's position by way of tilting and panning, along with the speed of movement and zoom level. In addition it allows setting the limits of both a device's position and speed of movement.
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-12T18:18:32.435+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "PositioningControl", 
                  wsdlLocation = "file:wsdl/PositioningControlV1.wsdl",
                  targetNamespace = "urn:schemas-pelco-com:service:PositioningControl:1") 
public class PositioningControl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:schemas-pelco-com:service:PositioningControl:1", "PositioningControl");
    public final static QName PositioningControl = new QName("urn:schemas-pelco-com:service:PositioningControl:1", "PositioningControl");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/PositioningControlV1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PositioningControl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:a/PositioningControlV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PositioningControl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PositioningControl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PositioningControl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PositioningControl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PositioningControl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PositioningControl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PositioningControlPortType
     */
    @WebEndpoint(name = "PositioningControl")
    public PositioningControlPortType getPositioningControl() {
        return super.getPort(PositioningControl, PositioningControlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PositioningControlPortType
     */
    @WebEndpoint(name = "PositioningControl")
    public PositioningControlPortType getPositioningControl(WebServiceFeature... features) {
        return super.getPort(PositioningControl, PositioningControlPortType.class, features);
    }

}
